--Drops the existing table 
DROP TABLE LMS_IMPORT_MEM_EARNINGS;

--Recreates the LMS_IMPORT_MEM_EARNINGS table
CREATE TABLE LMS_IMPORT_MEM_EARNINGS ( LIME_CODE NUMBER NOT NULL, LIME_PCM_CODE NUMBER(15),
 LIME_POLM_MEM_NO VARCHAR2(15 BYTE), LIME_MEM_SURNAME VARCHAR2(100 BYTE), LIME_MEM_OTHER_NAMES VARCHAR2(100 BYTE),
 LIME_EARNINGS NUMBER(15,5), LIME_PCM_MULT_EARNINGS_PRD NUMBER(7), LIME_PCA_CATEG_DESC VARCHAR2(60 BYTE), LMIE_ORIGINAL_LOAN_AMT NUMBER(25,5), 
 LMIE_LOAN_REPAYMENT_PRD NUMBER(5), LIME_BATCH_NO NUMBER(15), LIME_ENDR_CODE NUMBER(15), LIME_ADD_REMOVE VARCHAR2(10 BYTE), LIME_PMPNS_CODE NUMBER(15) );
 
 --add a primary key on LMS_IMPORT_MEM_EARNINGS
 ALTER TABLE LMS_IMPORT_MEM_EARNINGS ADD CONSTRAINT LMS_IMPORT_MEM_EARNINGS_PK PRIMARY KEY (LIME_CODE);