ALTER TABLE TQ_LMS.LMS_TAX_RATES
ADD (TRT_YRS_OF_SERVICE_FROM NUMBER(22,5));

COMMENT ON COLUMN 
TQ_LMS.LMS_TAX_RATES.TRT_YRS_OF_SERVICE_FROM IS 
'NO OF YEARS IN SERVICE FROM';

ALTER TABLE TQ_LMS.LMS_TAX_RATES
ADD (TRT_YRS_OF_SERVICE_TO NUMBER(22,5));

COMMENT ON COLUMN 
TQ_LMS.LMS_TAX_RATES.TRT_YRS_OF_SERVICE_TO IS 
'NO OF YEARS IN SERVICE TO';

ALTER TABLE TQ_LMS.LMS_TAX_RATES
ADD (TRT_CAUS_CODE NUMBER(15));

ALTER TABLE TQ_LMS.LMS_TAX_RATES
ADD CONSTRAINT TRT_CAUS_CODE_FK
FOREIGN KEY
  (TRT_CAUS_CODE)
REFERENCES
  TQ_LMS.LMS_CAUSATIONS
  (CAUS_CODE)
ENABLE
VALIDATE;

COMMENT ON COLUMN 
TQ_LMS.LMS_TAX_RATES.TRT_CAUS_CODE IS 
'TAX CAUSATION ';

ALTER TABLE TQ_LMS.LMS_TAX_RATES
ADD (TRT_APPLICABLE_AT_CAUS VARCHAR2(1 BYTE) DEFAULT 'N');

COMMENT ON COLUMN 
TQ_LMS.LMS_TAX_RATES.TRT_APPLICABLE_AT_CAUS IS 
'IF THE RATE IS APPLICABLE ON CAUSATION';


