begin
Insert into TQC_SYS_PROCESSES
   (SPRC_CODE, SPRC_SYS_CODE, SPRC_PROCESS, SPRC_BPM_ID, SPRC_SHT_DESC, 
    SPRC_JPDL_DESC)
 Values
   (730, 27, 'INITIAL SCHEDULE PROCESS', NULL, 'UWCT', 
    'EndorsementsProcess');
 Insert into TQC_SYS_PROCESS_AREAS
   (SPRCA_CODE, SPRCA_SPRC_CODE, SPRCA_AREA, SPRCA_SHT_DESC)
 Values
   (1479, 730, 'INITIAL SCHEDULE UNDEWRITING', 'DENTR');
      
 Insert into TQC_SYS_PROCESS_SUB_AREAS
   (SPRSA_CODE, SPRSA_SPRCA_CODE, SPRSA_SPRC_CODE, SPRSA_SUB_AREA, SPRSA_TYPE, 
    SPRSA_SHT_DESC, SPRSA_DEFAULT_USR_CODE)
 Values
   (1784, 1479, 730, 'Initial Schedule Details', 'C', 
    'CTDAT',NULL); 
Insert into TQC_SYS_PROCESS_AREAS
   (SPRCA_CODE, SPRCA_SPRC_CODE, SPRCA_AREA, SPRCA_SHT_DESC)
 Values
   (1480, 730, 'INITIAL SCHEDULE UNDEWRITING', 'CTUW');  
     
 Insert into TQC_SYS_PROCESS_SUB_AREAS
   (SPRSA_CODE, SPRSA_SPRCA_CODE, SPRSA_SPRC_CODE, SPRSA_SUB_AREA, SPRSA_TYPE, 
    SPRSA_SHT_DESC, SPRSA_DEFAULT_USR_CODE)
 Values
   (1785, 1480, 730, 'CT UW PROCESSING', 'C', 
    'CTUW', NULL);   
 Insert into TQC_SYS_PROCESS_SUB_AREAS
   (SPRSA_CODE, SPRSA_SPRCA_CODE, SPRSA_SPRC_CODE, SPRSA_SUB_AREA, SPRSA_TYPE, 
    SPRSA_SHT_DESC, SPRSA_DEFAULT_USR_CODE)
 Values
   (1786, 1480, 730, 'CT AUTHORIZATION', 'A', 
    'CTAU', NULL);
 Insert into TQC_SYS_PROCESS_AREAS
   (SPRCA_CODE, SPRCA_SPRC_CODE, SPRCA_AREA, SPRCA_SHT_DESC)
 Values
   (1481, 730, 'INITIAL SCHEDULE DISPATCH', 'EDISP');   
 Insert into TQC_SYS_PROCESS_SUB_AREAS
   (SPRSA_CODE, SPRSA_SPRCA_CODE, SPRSA_SPRC_CODE, SPRSA_SUB_AREA, SPRSA_TYPE, 
    SPRSA_SHT_DESC, SPRSA_DEFAULT_USR_CODE)
 Values
   (1787, 1481, 730, 'POLICY DOCUMENTS DISPATCH', 'C', 
    'EDISP', NULL);   
       
commit;

end;
/
