ALTER TABLE TQ_LMS.LMS_QUOTATION_AGENCIES
ADD (QUA_AGN_LEADER_FOLLOWER VARCHAR2(1 BYTE));
------------------------------------------------
ALTER TABLE TQ_LMS.LMS_QUOTATION_AGENCIES
ADD (qua_agn_share NUMBER);