begin
Insert into TQC_SYS_RPT_PARAMETERS
   (RPTP_CODE, RPTP_RPT_CODE, RPTP_PARAM_NAME, RPTP_PARAM_DESC, RPTP_PARAM_PROMPT, 
    RPTP_PARAM_TYPE, RPTP_PARENT_CODE, RPTP_QUERY, RPTP_PARAM_CLAUSE, RPTP_USER_REQUIRED, 
    RPTP_CHILD_CODE, RPTP_PARAM_ACTIVE)
 Values
   (25172, 2227, 'GRP_PRODUCT_POLICIES', 'Group Product Policies', 'Group Product Policies', 
    'LOV', NULL, 'SELECT * FROM LMS_POLICIES WHERE POL_CLA_SHT_DESC=''GRP''', NULL, NULL, 
    NULL, 'A');
Insert into TQC_SYS_RPT_PARAMETERS
   (RPTP_CODE, RPTP_RPT_CODE, RPTP_PARAM_NAME, RPTP_PARAM_DESC, RPTP_PARAM_PROMPT, 
    RPTP_PARAM_TYPE, RPTP_PARENT_CODE, RPTP_QUERY, RPTP_PARAM_CLAUSE, RPTP_USER_REQUIRED, 
    RPTP_CHILD_CODE, RPTP_PARAM_ACTIVE)
 Values
   (25173, 2227, 'V_DATE_FROM', 'DATE FROM', 'Date From', 
    'DATE', NULL, NULL, NULL, NULL, 
    NULL, 'A');
Insert into TQC_SYS_RPT_PARAMETERS
   (RPTP_CODE, RPTP_RPT_CODE, RPTP_PARAM_NAME, RPTP_PARAM_DESC, RPTP_PARAM_PROMPT, 
    RPTP_PARAM_TYPE, RPTP_PARENT_CODE, RPTP_QUERY, RPTP_PARAM_CLAUSE, RPTP_USER_REQUIRED, 
    RPTP_CHILD_CODE, RPTP_PARAM_ACTIVE)
 Values
   (25174, 2227, 'V_DATE_TO', 'DATE TO', 'Date To', 
    'DATE', NULL, NULL, NULL, NULL, 
    NULL, 'A');
COMMIT;
end;
/