BEGIN
Insert into TQC_SYSTEM_REPORTS
   (RPT_CODE, RPT_SYS_CODE, RPT_NAME, RPT_DESCRIPTION, RPT_DATA_FILE, 
    RPT_APPLCTN_LEVEL, RPT_ACTIVE)
 Values
   (2032, 27, 'NEW_SCHEME_REG', 'GL new Scheme report', 'NewSchemeReg.xml', 
    NULL, 'A');
Insert into TQC_SYS_RPT_TEMPLATES
   (RPT_TMPL_CODE, RPT_TMPL_RPT_CODE, RPT_TMPL_FILE, RPT_TMPL_NAME, RPT_TMPL_DESCRIPTION, 
    RPT_TMPL_STYLE_FILE, RPT_TMPL_ORG_CODE, RPT_TMPL_ACTIVE)
 Values
   (3360, 2032, 'NewSchemeReg_temp.rtf', 'NEW_SCHEME_REG', 'GL new Scheme Reg', 
    'NewSchemeReg_temp.xsl', NULL, 'A');
Insert into TQC_SYS_RPT_PARAMETERS
   (RPTP_CODE, RPTP_RPT_CODE, RPTP_PARAM_NAME, RPTP_PARAM_DESC, RPTP_PARAM_PROMPT, 
    RPTP_PARAM_TYPE, RPTP_PARENT_CODE, RPTP_QUERY, RPTP_PARAM_CLAUSE, RPTP_USER_REQUIRED, 
    RPTP_CHILD_CODE, RPTP_PARAM_ACTIVE)
 Values
   (24813, 2032, 'UP_DATE_FROM', 'START DATE', 'Start Date', 
    'DATE', NULL, NULL, NULL, NULL, 
    NULL, 'A');
Insert into TQC_SYS_RPT_PARAMETERS
   (RPTP_CODE, RPTP_RPT_CODE, RPTP_PARAM_NAME, RPTP_PARAM_DESC, RPTP_PARAM_PROMPT, 
    RPTP_PARAM_TYPE, RPTP_PARENT_CODE, RPTP_QUERY, RPTP_PARAM_CLAUSE, RPTP_USER_REQUIRED, 
    RPTP_CHILD_CODE, RPTP_PARAM_ACTIVE)
 Values
   (24814, 2032, 'UP_DATE_TO', 'END DATE', 'End Date', 
    'DATE', NULL, NULL, NULL, NULL, 
    NULL, 'A');
COMMIT;
END;
/

BEGIN
Insert into TQC_SYS_RPT_PARAMETERS
   (RPTP_CODE, RPTP_RPT_CODE, RPTP_PARAM_NAME, RPTP_PARAM_DESC, RPTP_PARAM_PROMPT, 
    RPTP_PARAM_TYPE, RPTP_PARENT_CODE, RPTP_QUERY, RPTP_PARAM_CLAUSE, RPTP_USER_REQUIRED, 
    RPTP_CHILD_CODE, RPTP_PARAM_ACTIVE)
 Values
   (24817,2032,'GRP_TRANS_TYPE','Group Life Transactions','Group Life Transactions', 
    'LOV', NULL, 'SELECT DISTINCT ENDR_TYPE,BTR_TRANS_TYPE FROM LMS_POLICY_ENDORSEMENTS,LMS_POLICIES,LMS_BUSINESS_TRANSACTIONS 
WHERE ENDR_TYPE=BTR_TRANS_CODE
AND ENDR_POL_CODE=POL_CODE
AND POL_PROD_SHT_DESC=''GLA''
AND ENDR_TYPE IN(''NB'',''RN'')
ORDER BY ENDR_TYPE ASC', NULL, NULL, 
    NULL, 'A');
COMMIT;
END;
/
