ALTER TABLE TQ_CRM.TQC_ACCOUNT_CONTACTS
ADD (ACCC_ACC_CODE NUMBER(15));

ALTER TABLE TQ_CRM.TQC_CLIENT_WEB_ACCOUNTS
ADD (ACWA_RESET_CODE VARCHAR2(100 BYTE));

ALTER TABLE TQ_CRM.TQC_BPM_TICKETS
ADD (TCKT_ADHOC_NAME VARCHAR2(100 BYTE));

ALTER TABLE TQ_CRM.TQC_BPM_TICKETS
ADD (TCKT_EXTERN_REF_NO VARCHAR2(100 BYTE));

ALTER TABLE TQ_CRM.TQC_BPM_TICKETS
ADD (TCKT_TYPE VARCHAR2(1 BYTE) DEFAULT 'S');

ALTER TABLE TQ_CRM.TQC_BPM_TICKETS
ADD (TCKT_CQR_NO NUMBER(15));

ALTER TABLE TQ_CRM.TQC_BPM_TICKETS
ADD (TCKT_CLA_TYPE VARCHAR2(5 BYTE));

ALTER TABLE TQ_CRM.tqc_memo_types
ADD (MTYP_SAA_CODE NUMBER(8));


CREATE TABLE TQ_CRM.TQC_EMBASSY_CONTACTS
(
  ACCC_CODE             NUMBER(15),
  ACCC_COU_CODE         NUMBER(8),
  ACCC_NAME             VARCHAR2(75 BYTE),
  ACCC_OTHER_NAMES      VARCHAR2(100 BYTE),
  ACCC_DOB              DATE,
  ACCC_TEL              VARCHAR2(35 BYTE),
  ACCC_EMAIL_ADDR       VARCHAR2(100 BYTE),
  ACCC_SMS_TEL          VARCHAR2(35 BYTE),
  ACCC_USERNAME         VARCHAR2(15 BYTE),
  ACCC_PWD              VARCHAR2(50 BYTE),
  ACCC_LOGIN_ALLOWED    VARCHAR2(1 BYTE)        DEFAULT 'N',
  ACCC_PWD_CHANGED      DATE,
  ACCC_PWD_RESET        VARCHAR2(2 BYTE),
  ACCC_DT_CREATED       DATE,
  ACCC_STATUS           VARCHAR2(2 BYTE),
  ACCC_LOGIN_ATTEMPTS   NUMBER(8),
  ACCC_PERSONEL_RANK    VARCHAR2(50 BYTE),
  ACCC_LAST_LOGIN_DATE  DATE,
  ACCC_CREATED_BY       VARCHAR2(50 BYTE)
)
TABLESPACE CRMDATA
PCTUSED    40
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


--  There is no statement for index TQ_CRM.SYS_C0078456.
--  The object is created automatically by Oracle when the parent object is created.

ALTER TABLE TQ_CRM.TQC_EMBASSY_CONTACTS ADD (
  PRIMARY KEY
  (ACCC_CODE)
  USING INDEX
    TABLESPACE CRMDATA
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          64K
                MINEXTENTS       1
                MAXEXTENTS       UNLIMITED
                PCTINCREASE      0
                FREELISTS        1
                FREELIST GROUPS  1
               ));

ALTER TABLE TQ_CRM.TQC_EMBASSY_CONTACTS ADD (
  FOREIGN KEY (ACCC_COU_CODE) 
  REFERENCES TQ_CRM.TQC_COUNTRIES (COU_CODE));
  
CREATE TABLE TQ_CRM.TQC_ACC_EMBASSY_PWD_HIST
(
  ACCPH_CODE           NUMBER(20),
  ACCPH_ACCC_CODE      NUMBER(8),
  ACCPH_ACCC_USERNAME  VARCHAR2(15 BYTE),
  ACCPH_PWD            VARCHAR2(65 BYTE),
  ACCPH_PWD_CHANGE_DT  DATE,
  ACCC_PWD_CHANGE_BY   VARCHAR2(15 BYTE)
)
TABLESPACE CRMDATA
PCTUSED    40
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

CREATE TABLE TQ_CRM.TQC_SYS_APPLICABLE_AREAS
(
  SAA_CODE         NUMBER(8)                    NOT NULL,
  SAA_SYS_CODE     NUMBER(8)                    NOT NULL,
  SAA_DESCRIPTION  VARCHAR2(100 BYTE)           NOT NULL
)
TABLESPACE CRMDATA
PCTUSED    40
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX TQ_CRM.TQC_SYS_APPLICABLE_AREAS_PK ON TQ_CRM.TQC_SYS_APPLICABLE_AREAS
(SAA_CODE)
LOGGING
TABLESPACE CRMDATA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


ALTER TABLE TQ_CRM.TQC_SYS_APPLICABLE_AREAS ADD (
  CONSTRAINT TQC_SYS_APPLICABLE_AREAS_PK
  PRIMARY KEY
  (SAA_CODE)
  USING INDEX TQ_CRM.TQC_SYS_APPLICABLE_AREAS_PK);

ALTER TABLE TQ_CRM.TQC_SYS_APPLICABLE_AREAS ADD (
  CONSTRAINT SAA_SYS_CODE_FK 
  FOREIGN KEY (SAA_SYS_CODE) 
  REFERENCES TQ_CRM.TQC_SYSTEMS (SYS_CODE));













