ALTER TABLE TQ_LMS.LMS_PARAMETERS
ADD (PARAM_CLA_CODE VARCHAR2(5 BYTE));



SET DEFINE OFF;
Insert into TQ_LMS.LMS_PARAMETERS
   (PARAM_CODE, PARAM_NAME, PARAM_VALUE, PARAM_STATUS, PARAM_DESC, PARAM_PROD_SPECIFIC, PARAM_CLA_CODE, PARAM_CLA_TYPE)
 Values
   (201144, 'THIRD_PARTY_CRM_INTERFACE', 'N', 'A', 'IF THE SYSTEM INTERFACES TO A THIRD PARTY CRM FOR CLIENTS, INTERMEDIARIES AND INSURERS', 
    'N', '20022', 'G');
COMMIT;

ALTER TABLE TQ_LMS.LMS_QUOTATIONS
ADD (QUO_UMBRELLA VARCHAR2(1 BYTE) DEFAULT 'N');


ALTER TABLE TQ_LMS.LMS_PRODUCTS
ADD (PROD_PENS_CONTRI_LIMIT NUMBER(15,5));

ALTER TABLE TQ_LMS.LMS_QUOTATIONS
ADD (QUO_MKTR_AGN_CODE NUMBER(22));

ALTER TABLE TQ_LMS.LMS_QUOTATIONS
ADD (QUO_MKTR_AGN_SHT_DESC  VARCHAR2 (20 Byte));

ALTER TABLE TQ_LMS.LMS_QUOTATIONS
ADD (QUO_OS_LOAN_CALC  VARCHAR2 (1 Byte));

ALTER TABLE TQ_LMS.LMS_QUOTATIONS
ADD (QUO_PENS_MODE  VARCHAR2 (5 Byte));

ALTER TABLE TQ_LMS.LMS_QUOTATIONS
ADD (QUO_ANN_SCHEME_LEGAL_AGE NUMBER(10, 5));

ALTER TABLE TQ_LMS.LMS_QUOTATIONS
ADD (QUO_ANN_INVEST_INTR_RATE NUMBER(10, 5));

ALTER TABLE TQ_LMS.LMS_QUOTATIONS
ADD (QUO_ANN_ADMIN_CHARGE NUMBER(10, 5));

ALTER TABLE TQ_LMS.LMS_QUOTATIONS
ADD (QUO_ANN_TERMINAL_PAYOUT_RATE NUMBER(10, 5));

ALTER TABLE TQ_LMS.LMS_QUOTATIONS
ADD (QUO_ANN_INVESTMENT_RATE NUMBER(10, 5));

ALTER TABLE TQ_LMS.LMS_QUOTATIONS
MODIFY(QUO_DURATION_TERM_TYPE VARCHAR2(3 BYTE));

ALTER TABLE TQ_LMS.LMS_QUOTATION_COVER_TYPES
ADD (QCVT_USE_CVR_RATE VARCHAR2(1 BYTE) DEFAULT 'M');

ALTER TABLE TQ_LMS.LMS_QUOTATION_COVER_TYPES
ADD (QCVT_DISC_DIV_FACT NUMBER(15));

ALTER TABLE TQ_LMS.LMS_QUOTATION_COVER_TYPES
ADD (QCVT_DISC_RATE NUMBER(25, 5));

ALTER TABLE TQ_LMS.LMS_QUOTATION_COVER_TYPES
ADD (QCVT_DISC VARCHAR2(100 BYTE));

ALTER TABLE TQ_LMS.LMS_QUOTATION_COVER_TYPES
ADD (QCVT_LOANAMT_PER_MEM NUMBER(23, 5));

ALTER TABLE TQ_LMS.LMS_QUOTATION_COVER_TYPES
ADD (QCVT_LOAN_RPYMT_PRD NUMBER(23, 5));

ALTER TABLE TQ_LMS.LMS_QUOTATION_COVER_TYPES
ADD (QCVT_LOANINT_PER_MEM NUMBER(23, 5));

ALTER TABLE TQ_LMS.LMS_QUOTATION_COVER_TYPES
ADD (QCVT_SAVINGS_PER_MEM NUMBER(23, 5));

ALTER TABLE TQ_LMS.LMS_QCVT_DEPENDENT_LIMITS
ADD (QDL_MIN_AMT NUMBER(22,5));

ALTER TABLE TQ_LMS.LMS_POL_DEPENDENT_LIMITS
ADD (PDL_MIN_AMT NUMBER(22,5));

ALTER TABLE TQ_LMS.LMS_QUOTATION_CATEGORIES
ADD (LCA_PMAS_CODE NUMBER(22,5));

ALTER TABLE TQ_LMS.LMS_QUOTATION_CATEGORIES
ADD (LCA_SCH_CODE NUMBER(22,5));

ALTER TABLE TQ_LMS.LMS_POLICY_CATEGORIES
ADD (PCA_PMAS_CODE NUMBER(22,5));

ALTER TABLE TQ_LMS.LMS_POLICY_CATEGORIES
ADD (PCA_LPAG_CODE NUMBER(22,5));

ALTER TABLE TQ_LMS.LMS_POLICY_CATEGORIES
ADD (PCA_SCH_CODE NUMBER(22,5));


ALTER TABLE TQ_LMS.LMS_PROD_CVT_DEPENDANTS
ADD (PCD_DEFAULT VARCHAR2(1 BYTE) DEFAULT 'N');

DROP TABLE TQ_LMS.LMS_CLASS_TERM_LIMITS CASCADE CONSTRAINTS;

CREATE TABLE TQ_LMS.LMS_CLASS_TERM_LIMITS
(
  CTL_CODE           NUMBER(20),
  CTL_QUO_LCA_CODE   NUMBER(20),
  CTL_TERM_DESC      VARCHAR2(25 BYTE),
  CTL_FEE_AMOUNT     NUMBER(20),
  CTL_QUO_CODE       NUMBER(20),
  CTL_TERM_SHT_DESC  VARCHAR2(5 BYTE),
  CTL_AV_STUDENTS    NUMBER(22)
)
TABLESPACE LMSDATA
PCTUSED    40
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE INDEX TQ_LMS.CTL_QUO_LCA_CODE_IDX ON TQ_LMS.LMS_CLASS_TERM_LIMITS
(CTL_QUO_LCA_CODE)
LOGGING
TABLESPACE LMSDATA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


DROP PUBLIC SYNONYM LMS_CLASS_TERM_LIMITS;

CREATE OR REPLACE PUBLIC SYNONYM LMS_CLASS_TERM_LIMITS FOR TQ_LMS.LMS_CLASS_TERM_LIMITS;


ALTER TABLE TQ_LMS.LMS_CLASS_TERM_LIMITS ADD (
  CONSTRAINT QUO_LCA_CODE_FK 
  FOREIGN KEY (CTL_QUO_LCA_CODE) 
  REFERENCES TQ_LMS.LMS_QUOTATION_CATEGORIES (LCA_CODE));
  

ALTER TABLE TQ_LMS.LMS_QUOTATIONS
ADD (QUO_UMBRELLA_DURATION VARCHAR2(1 BYTE));

CREATE TABLE TQ_LMS.LMS_GRP_SUBDIVISIONS
(
  GSUB_CODE      NUMBER(22),
  GSUB_SHT_DESC  VARCHAR2(20 BYTE),
  GSUB_DESC      VARCHAR2(100 BYTE)
)
TABLESPACE LMSDATA
PCTUSED    40
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX TQ_LMS.LMS_GRP_SUBDIVISIONS_PK ON TQ_LMS.LMS_GRP_SUBDIVISIONS
(GSUB_CODE)
LOGGING
TABLESPACE LMSDATA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


ALTER TABLE TQ_LMS.LMS_GRP_SUBDIVISIONS ADD (
  CONSTRAINT LMS_GRP_SUBDIVISIONS_PK
  PRIMARY KEY
  (GSUB_CODE)
  USING INDEX TQ_LMS.LMS_GRP_SUBDIVISIONS_PK);
  
  
CREATE TABLE TQ_LMS.LMS_QUOTE_GRP_SUBDIVISIONS
(
  QGSUB_CODE       NUMBER(22),
  QGSUB_QUO_CODE   NUMBER(22,5),
  QGSUB_GSUB_CODE  NUMBER(22),
  QGSUB_SHT_DESC   VARCHAR2(20 BYTE),
  QGSUB_DESC       VARCHAR2(100 BYTE),
  QGSUB_PREV_CODE  NUMBER(22)
)
TABLESPACE LMSDATA
PCTUSED    40
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX TQ_LMS.LMS_QUOTE_GRP_SUBDIVISIONS_PK ON TQ_LMS.LMS_QUOTE_GRP_SUBDIVISIONS
(QGSUB_CODE)
LOGGING
TABLESPACE LMSDATA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE INDEX TQ_LMS.QGSUB_GSUB_CODE_IDX ON TQ_LMS.LMS_QUOTE_GRP_SUBDIVISIONS
(QGSUB_GSUB_CODE)
LOGGING
TABLESPACE LMSDATA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE INDEX TQ_LMS.QGSUB_QUO_CODE_IDX ON TQ_LMS.LMS_QUOTE_GRP_SUBDIVISIONS
(QGSUB_QUO_CODE)
LOGGING
TABLESPACE LMSDATA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


ALTER TABLE TQ_LMS.LMS_QUOTE_GRP_SUBDIVISIONS ADD (
  CONSTRAINT LMS_QUOTE_GRP_SUBDIVISIONS_PK
  PRIMARY KEY
  (QGSUB_CODE)
  USING INDEX TQ_LMS.LMS_QUOTE_GRP_SUBDIVISIONS_PK);

ALTER TABLE TQ_LMS.LMS_QUOTE_GRP_SUBDIVISIONS ADD (
  CONSTRAINT LMS_QUOTE_GRP_SUBDIVISIONS_R01 
  FOREIGN KEY (QGSUB_QUO_CODE) 
  REFERENCES TQ_LMS.LMS_QUOTATIONS (QUO_CODE),
  CONSTRAINT LMS_QUOTE_GRP_SUBDIVISIONS_R02 
  FOREIGN KEY (QGSUB_GSUB_CODE) 
  REFERENCES TQ_LMS.LMS_GRP_SUBDIVISIONS (GSUB_CODE));


CREATE TABLE TQ_LMS.LMS_QUOTE_MEM_SUBDIVISIONS
(
  QMEMS_CODE        NUMBER(25),
  QMEMS_QMEM_CODE   NUMBER(25),
  QMEMS_QGSUB_CODE  NUMBER(22),
  QMEMS_SHT_DESC    VARCHAR2(50 BYTE),
  QMEMS_QUO_CODE    NUMBER(22)
)
TABLESPACE LMSDATA
PCTUSED    40
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE INDEX TQ_LMS.QMEMS_QGSUB_CODE_IDX ON TQ_LMS.LMS_QUOTE_MEM_SUBDIVISIONS
(QMEMS_QGSUB_CODE)
LOGGING
TABLESPACE LMSDATA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE INDEX TQ_LMS.QMEMS_QMEM_CODE_IDX ON TQ_LMS.LMS_QUOTE_MEM_SUBDIVISIONS
(QMEMS_QMEM_CODE)
LOGGING
TABLESPACE LMSDATA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE INDEX TQ_LMS.QMEMS_QUO_CODE_IDX ON TQ_LMS.LMS_QUOTE_MEM_SUBDIVISIONS
(QMEMS_QUO_CODE)
LOGGING
TABLESPACE LMSDATA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


ALTER TABLE TQ_LMS.LMS_QUOTE_MEM_SUBDIVISIONS ADD (
  CONSTRAINT LMS_QUOTATION_MEM_SUBDIVIS_R01 
  FOREIGN KEY (QMEMS_QMEM_CODE) 
  REFERENCES TQ_LMS.LMS_QUOTATION_MEMBERS (QMEM_CODE),
  CONSTRAINT LMS_QUOTATION_MEM_SUBDIVIS_R02 
  FOREIGN KEY (QMEMS_QGSUB_CODE) 
  REFERENCES TQ_LMS.LMS_QUOTE_GRP_SUBDIVISIONS (QGSUB_CODE),
  CONSTRAINT LMS_QUOTATION_MEM_SUBDIVIS_R03 
  FOREIGN KEY (QMEMS_QUO_CODE) 
  REFERENCES TQ_LMS.LMS_QUOTATIONS (QUO_CODE));

CREATE TABLE TQ_LMS.LMS_POLICY_GRP_SUBDIVISIONS
(
  PGSUB_CODE        NUMBER(22),
  PGSUB_POL_CODE    NUMBER(25,5),
  PGSUB_ENDR_CODE   NUMBER(25,5),
  PGSUB_GSUB_CODE   NUMBER(22),
  PGSUB_SHT_DESC    VARCHAR2(20 BYTE),
  PGSUB_DESC        VARCHAR2(100 BYTE),
  PGSUB_QGSUB_CODE  NUMBER(22)
)
TABLESPACE LMSDATA
PCTUSED    40
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX TQ_LMS.LMS_POLICY_GRP_SUBDIVISIONS_PK ON TQ_LMS.LMS_POLICY_GRP_SUBDIVISIONS
(PGSUB_CODE)
LOGGING
TABLESPACE LMSDATA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE INDEX TQ_LMS.PGSUB_ENDR_CODE_IDX ON TQ_LMS.LMS_POLICY_GRP_SUBDIVISIONS
(PGSUB_ENDR_CODE)
LOGGING
TABLESPACE LMSDATA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE INDEX TQ_LMS.PGSUB_POL_CODE_IDX ON TQ_LMS.LMS_POLICY_GRP_SUBDIVISIONS
(PGSUB_POL_CODE)
LOGGING
TABLESPACE LMSDATA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


ALTER TABLE TQ_LMS.LMS_POLICY_GRP_SUBDIVISIONS ADD (
  CONSTRAINT LMS_POLICY_GRP_SUBDIVISIONS_PK
  PRIMARY KEY
  (PGSUB_CODE)
  USING INDEX TQ_LMS.LMS_POLICY_GRP_SUBDIVISIONS_PK);

ALTER TABLE TQ_LMS.LMS_POLICY_GRP_SUBDIVISIONS ADD (
  CONSTRAINT LMS_POLICY_GRP_SUBDIVISIONSR01 
  FOREIGN KEY (PGSUB_POL_CODE) 
  REFERENCES TQ_LMS.LMS_POLICIES (POL_CODE),
  CONSTRAINT LMS_POLICY_GRP_SUBDIVISIONSR02 
  FOREIGN KEY (PGSUB_ENDR_CODE) 
  REFERENCES TQ_LMS.LMS_POLICY_ENDORSEMENTS (ENDR_CODE));
  
  CREATE TABLE TQ_LMS.LMS_POLICY_MEM_SUBDIVISIONS
(
  PMEMS_CODE        NUMBER(25),
  PMEMS_POLM_CODE   NUMBER(25),
  PMEMS_PGSUB_CODE  NUMBER(22),
  PMEMS_SHT_DESC    VARCHAR2(50 BYTE),
  PMEMS_ENDR_CODE   NUMBER(25),
  PMEMS_POL_CODE    NUMBER(25)
)
TABLESPACE LMSDATA
PCTUSED    40
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX TQ_LMS.LMS_POLICY_MEM_SUBDIVISIONS_PK ON TQ_LMS.LMS_POLICY_MEM_SUBDIVISIONS
(PMEMS_CODE)
LOGGING
TABLESPACE LMSDATA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE INDEX TQ_LMS.PMEMS_ENDR_CODE_IDX ON TQ_LMS.LMS_POLICY_MEM_SUBDIVISIONS
(PMEMS_ENDR_CODE)
LOGGING
TABLESPACE LMSDATA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE INDEX TQ_LMS.PMEMS_PGSUB_CODE_IDX ON TQ_LMS.LMS_POLICY_MEM_SUBDIVISIONS
(PMEMS_PGSUB_CODE)
LOGGING
TABLESPACE LMSDATA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE INDEX TQ_LMS.PMEMS_POLM_CODE_IDX ON TQ_LMS.LMS_POLICY_MEM_SUBDIVISIONS
(PMEMS_POLM_CODE)
LOGGING
TABLESPACE LMSDATA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


ALTER TABLE TQ_LMS.LMS_POLICY_MEM_SUBDIVISIONS ADD (
  CONSTRAINT LMS_POLICY_MEM_SUBDIVISIONS_PK
  PRIMARY KEY
  (PMEMS_CODE)
  USING INDEX TQ_LMS.LMS_POLICY_MEM_SUBDIVISIONS_PK);

ALTER TABLE TQ_LMS.LMS_POLICY_MEM_SUBDIVISIONS ADD (
  CONSTRAINT LMS_POLICY_MEM_SUBDIVISIONSR01 
  FOREIGN KEY (PMEMS_PGSUB_CODE) 
  REFERENCES TQ_LMS.LMS_POLICY_GRP_SUBDIVISIONS (PGSUB_CODE),
  CONSTRAINT LMS_POLICY_MEM_SUBDIVISIONSR02 
  FOREIGN KEY (PMEMS_POLM_CODE) 
  REFERENCES TQ_LMS.LMS_POLICY_MEMBERS (POLM_CODE),
  CONSTRAINT LMS_POLICY_MEM_SUBDIVISIONSR03 
  FOREIGN KEY (PMEMS_ENDR_CODE) 
  REFERENCES TQ_LMS.LMS_POLICY_ENDORSEMENTS (ENDR_CODE));
  
  
  ALTER TABLE TQ_LMS.LMS_AGENCY_CONTACTS
 DROP PRIMARY KEY CASCADE;

DROP TABLE TQ_LMS.LMS_AGENCY_CONTACTS CASCADE CONSTRAINTS;

CREATE TABLE TQ_LMS.LMS_AGENCY_CONTACTS
(
  LAC_CODE            NUMBER(15)                NOT NULL,
  LAC_CONTACT_PERSON  VARCHAR2(60 BYTE)         NOT NULL,
  LAC_CONTACT_TITLE   VARCHAR2(60 BYTE),
  LAC_AGN_CODE        NUMBER(15)                NOT NULL,
  LAC_TELEPHONE       VARCHAR2(50 BYTE),
  LAC_SEX             VARCHAR2(1 BYTE),
  LAC_ADDRESS         VARCHAR2(50 BYTE),
  LAC_CONTACT_NAME    VARCHAR2(100 BYTE),
  LAC_CONTACT_EMAIL   VARCHAR2(50 BYTE)
)
TABLESPACE LMSDATA
PCTUSED    40
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX TQ_LMS.PK_LMS_AGENCY_CONTACTS ON TQ_LMS.LMS_AGENCY_CONTACTS
(LAC_CODE)
NOLOGGING
TABLESPACE LMSDATA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


DROP PUBLIC SYNONYM LMS_AGENCY_CONTACTS;

CREATE OR REPLACE PUBLIC SYNONYM LMS_AGENCY_CONTACTS FOR TQ_LMS.LMS_AGENCY_CONTACTS;


ALTER TABLE TQ_LMS.LMS_AGENCY_CONTACTS ADD (
  CONSTRAINT PK_LMS_AGENCY_CONTACTS
  PRIMARY KEY
  (LAC_CODE)
  USING INDEX TQ_LMS.PK_LMS_AGENCY_CONTACTS);

ALTER TABLE TQ_LMS.LMS_CR_DR_NARRATIVES
ADD (DRCR_END_NARRATIVE VARCHAR2(4000 BYTE));

ALTER TABLE TQ_LMS.LMS_CR_DR_NARRATIVES
ADD (DRCR_DR_COIN_NARRATIVE VARCHAR2(300 BYTE));

ALTER TABLE TQ_LMS.LMS_CR_DR_NARRATIVES
ADD (DRCR_CR_COIN_NARRATIVE VARCHAR2(300 BYTE));

ALTER TABLE TQ_LMS.LMS_TAX_RATES
 DROP PRIMARY KEY CASCADE;

DROP TABLE TQ_LMS.LMS_TAX_RATES CASCADE CONSTRAINTS;

CREATE TABLE TQ_LMS.LMS_TAX_RATES
(
  TRT_CODE                 NUMBER(15)           DEFAULT 0                     NOT NULL,
  TRT_RATE                 NUMBER(30,5)         DEFAULT 0,
  TRT_WEF_DATE             DATE,
  TRT_WET_DATE             DATE,
  TRT_RANGE_FROM           NUMBER(20,5)         DEFAULT 0,
  TRT_RANGE_TO             NUMBER(20,5)         DEFAULT 0,
  TRT_DIVISION_FACTOR      NUMBER(7)            DEFAULT 0,
  TRT_TT_CODE              NUMBER(15)           NOT NULL,
  TRT_PROD_CODE            NUMBER(15),
  TRT_RATE_TYPE            VARCHAR2(3 BYTE),
  TRT_APPLICATION_FREQ     VARCHAR2(5 BYTE)     DEFAULT 'O'                   NOT NULL,
  TRT_APPLIED_TO           VARCHAR2(5 BYTE)     DEFAULT 'CO'                  NOT NULL,
  TRT_TAX_DURATION         NUMBER(10,5),
  TRT_AGE_FROM             NUMBER(10,5)         DEFAULT 0                     NOT NULL,
  TRT_AGE_TO               NUMBER(10,5)         DEFAULT 99                    NOT NULL,
  TRT_PCT_CODE             NUMBER(15),
  TRT_CLA_CODE             NUMBER(15),
  TRT_SINGLE_RATE          NUMBER(23,5),
  TRT_FREQ_OF_PAY          VARCHAR2(5 BYTE),
  TRT_CAUS_CODE            NUMBER(15),
  TRT_YRS_OF_SERVICE_FROM  NUMBER(22,5),
  TRT_YRS_OF_SERVICE_TO    NUMBER(22,5),
  TRT_APPLICABLE_AT_CAUS   VARCHAR2(1 BYTE)     DEFAULT 'N'
)
TABLESPACE LMSDATA
PCTUSED    40
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

COMMENT ON TABLE TQ_LMS.LMS_TAX_RATES IS 'STORES TAX RATES';

COMMENT ON COLUMN TQ_LMS.LMS_TAX_RATES.TRT_CODE IS 'UNIQUE CODE';

COMMENT ON COLUMN TQ_LMS.LMS_TAX_RATES.TRT_RATE IS 'RATE';

COMMENT ON COLUMN TQ_LMS.LMS_TAX_RATES.TRT_WEF_DATE IS 'WEF';

COMMENT ON COLUMN TQ_LMS.LMS_TAX_RATES.TRT_WET_DATE IS 'WET';

COMMENT ON COLUMN TQ_LMS.LMS_TAX_RATES.TRT_RANGE_FROM IS 'RANGE FROM';

COMMENT ON COLUMN TQ_LMS.LMS_TAX_RATES.TRT_RANGE_TO IS 'RANGE TO';

COMMENT ON COLUMN TQ_LMS.LMS_TAX_RATES.TRT_DIVISION_FACTOR IS 'DIVISION FACTOR';

COMMENT ON COLUMN TQ_LMS.LMS_TAX_RATES.TRT_TT_CODE IS 'TAX TYPE CODE';

COMMENT ON COLUMN TQ_LMS.LMS_TAX_RATES.TRT_PROD_CODE IS 'PRODUCT CODE';

COMMENT ON COLUMN TQ_LMS.LMS_TAX_RATES.TRT_RATE_TYPE IS 'RATE TYPE ( FIXED,'' FXD'', RECURRING, ''RCU '', RANGE ABSOLUTE, '' ARG'', RANGE STEP, ''SRG '')';

COMMENT ON COLUMN TQ_LMS.LMS_TAX_RATES.TRT_APPLICATION_FREQ IS '(O)NCE, (R)ENEWAL, (A)LWAYS';

COMMENT ON COLUMN TQ_LMS.LMS_TAX_RATES.TRT_APPLIED_TO IS '(CO)MPANY, (CL)IENT';

COMMENT ON COLUMN TQ_LMS.LMS_TAX_RATES.TRT_CAUS_CODE IS 'TAX CAUSATION ';

COMMENT ON COLUMN TQ_LMS.LMS_TAX_RATES.TRT_YRS_OF_SERVICE_FROM IS 'NO OF YEARS IN SERVICE FROM';

COMMENT ON COLUMN TQ_LMS.LMS_TAX_RATES.TRT_YRS_OF_SERVICE_TO IS 'NO OF YEARS IN SERVICE TO';

COMMENT ON COLUMN TQ_LMS.LMS_TAX_RATES.TRT_APPLICABLE_AT_CAUS IS 'IF THE RATE IS APPLICABLE ON CAUSATION';



CREATE UNIQUE INDEX TQ_LMS.DUPLICATE_TAX_RATES ON TQ_LMS.LMS_TAX_RATES
(TRT_TT_CODE, TRT_PROD_CODE, TRT_AGE_FROM, TRT_AGE_TO, TRT_FREQ_OF_PAY, 
TRT_RANGE_FROM, TRT_RANGE_TO, TRT_RATE_TYPE)
LOGGING
TABLESPACE LMSDATA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE INDEX TQ_LMS.TRT_APPLIED_TO_IDX ON TQ_LMS.LMS_TAX_RATES
(TRT_APPLIED_TO)
LOGGING
TABLESPACE LMSDATA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE INDEX TQ_LMS.TRT_APPL_FREQ_IDX ON TQ_LMS.LMS_TAX_RATES
(TRT_APPLICATION_FREQ)
LOGGING
TABLESPACE LMSDATA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE UNIQUE INDEX TQ_LMS.TRT_PK ON TQ_LMS.LMS_TAX_RATES
(TRT_CODE)
NOLOGGING
TABLESPACE LMSDATA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE INDEX TQ_LMS.TRT_PROD_FK_I ON TQ_LMS.LMS_TAX_RATES
(TRT_PROD_CODE)
NOLOGGING
TABLESPACE LMSDATA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE INDEX TQ_LMS.TRT_RANGE_FROM_TO_IND ON TQ_LMS.LMS_TAX_RATES
(TRT_RANGE_FROM, TRT_RANGE_TO)
NOLOGGING
TABLESPACE LMSDATA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE INDEX TQ_LMS.TRT_TAX_DURATION_IDX ON TQ_LMS.LMS_TAX_RATES
(TRT_TAX_DURATION)
LOGGING
TABLESPACE LMSDATA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE INDEX TQ_LMS.TRT_TT_FK_I ON TQ_LMS.LMS_TAX_RATES
(TRT_TT_CODE)
NOLOGGING
TABLESPACE LMSDATA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


DROP PUBLIC SYNONYM LMS_TAX_RATES;

CREATE OR REPLACE PUBLIC SYNONYM LMS_TAX_RATES FOR TQ_LMS.LMS_TAX_RATES;


ALTER TABLE TQ_LMS.LMS_TAX_RATES ADD (
  CONSTRAINT TRT_PK
  PRIMARY KEY
  (TRT_CODE)
  USING INDEX TQ_LMS.TRT_PK,
  CONSTRAINT DUPLICATE_TAX_RATES
  UNIQUE (TRT_TT_CODE, TRT_PROD_CODE, TRT_AGE_FROM, TRT_AGE_TO, TRT_FREQ_OF_PAY, TRT_RANGE_FROM, TRT_RANGE_TO, TRT_RATE_TYPE)
  USING INDEX TQ_LMS.DUPLICATE_TAX_RATES);

ALTER TABLE TQ_LMS.LMS_TAX_RATES ADD (
  CONSTRAINT TRT_CAUS_CODE_FK 
  FOREIGN KEY (TRT_CAUS_CODE) 
  REFERENCES TQ_LMS.LMS_CAUSATIONS (CAUS_CODE),
  CONSTRAINT TRT_PROD_FK 
  FOREIGN KEY (TRT_PROD_CODE) 
  REFERENCES TQ_LMS.LMS_PRODUCTS (PROD_CODE));
 
ALTER TABLE TQ_LMS.LMS_PROD_COVER_TYPES
ADD (PCT_SA_DEPEND_ON_LIMIT VARCHAR2(1 BYTE) DEFAULT 'N');

ALTER TABLE TQ_LMS.LMS_PRODUCTS
ADD (PROD_STATUS VARCHAR2(10 BYTE));

ALTER TABLE TQ_LMS.LMS_PRODUCTS
ADD (PROD_PENS_TYPE VARCHAR2(5 BYTE));

ALTER TABLE TQ_LMS.LMS_PRODUCTS
ADD (PROD_LOAN_GUARD VARCHAR2(1 BYTE));

ALTER TABLE TQ_LMS.LMS_PRODUCTS
ADD (PROD_FMS_RECEIPTING VARCHAR2(1 BYTE) DEFAULT 'D');

ALTER TABLE TQ_LMS.LMS_PRODUCTS
ADD (PROD_QUO_EXPIRY_PRD NUMBER(22));

ALTER TABLE TQ_LMS.LMS_ANNUITY_TYPE_RATES
ADD (ANNTR_GENDER VARCHAR2(1 BYTE));

ALTER TABLE TQ_LMS.LMS_CAUSATIONS
ADD (CAUS_WTHLD_EMPLE_FND  VARCHAR2(1 BYTE) DEFAULT 'N');

ALTER TABLE TQ_LMS.LMS_CAUSATIONS
ADD (CAUS_AGE_FROM NUMBER(15));

ALTER TABLE TQ_LMS.LMS_CAUSATIONS
ADD (CAUS_AGE_TO NUMBER(15));

ALTER TABLE TQ_LMS.LMS_PENSION_TABLES
ADD (LPNT_DEFAULT VARCHAR2(1 BYTE) DEFAULT 'N');

CREATE TABLE TQ_LMS.LMS_PENS_VESTING_SCALE
(
  PVGS_CODE          NUMBER(15)                 NOT NULL,
  PVGS_PROD_CODE     NUMBER(15)                 NOT NULL,
  PVGS_YRS_FROM      NUMBER(4)                  NOT NULL,
  PVGS_YRS_TO        NUMBER(4)                  NOT NULL,
  PVGS_EMYR_PCT_ENT  NUMBER(10,3)               NOT NULL,
  PVGS_EMYE_PCT_ENT  NUMBER(10,3)               NOT NULL
)
TABLESPACE LMSDATA
PCTUSED    40
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX TQ_LMS.PVGS_PK ON TQ_LMS.LMS_PENS_VESTING_SCALE
(PVGS_CODE)
NOLOGGING
TABLESPACE LMSDATA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE INDEX TQ_LMS.PVGS_PROD_CODE_IDX ON TQ_LMS.LMS_PENS_VESTING_SCALE
(PVGS_PROD_CODE)
LOGGING
TABLESPACE LMSDATA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;

CREATE OR REPLACE PUBLIC SYNONYM LMS_PENS_VESTING_SCALE FOR TQ_LMS.LMS_PENS_VESTING_SCALE;


ALTER TABLE TQ_LMS.LMS_PENS_VESTING_SCALE ADD (
  CONSTRAINT PVGS_PK
  PRIMARY KEY
  (PVGS_CODE)
  USING INDEX TQ_LMS.PVGS_PK);

ALTER TABLE TQ_LMS.LMS_PENS_VESTING_SCALE ADD (
  CONSTRAINT PVGS_PROD_CODE_PK 
  FOREIGN KEY (PVGS_PROD_CODE) 
  REFERENCES TQ_LMS.LMS_PRODUCTS (PROD_CODE));
  
 
CREATE TABLE TQ_LMS.LMS_PROD_IMP_TMPLT
(
  LPIT_CODE            NUMBER(25),
  LPIT_PROD_CODE       NUMBER(22),
  LPIT_TABLE_NAME      VARCHAR2(50 BYTE),
  LPIT_COL1_NAME       VARCHAR2(20 BYTE),
  LPIT_COL1_POSITION   NUMBER(5),
  LPIT_COL1_MAPPING    VARCHAR2(50 BYTE),
  LPIT_COL2_NAME       VARCHAR2(20 BYTE),
  LPIT_COL2_POSITION   NUMBER(5),
  LPIT_COL2_MAPPING    VARCHAR2(50 BYTE),
  LPIT_COL3_NAME       VARCHAR2(20 BYTE),
  LPIT_COL3_POSITION   NUMBER(5),
  LPIT_COL3_MAPPING    VARCHAR2(50 BYTE),
  LPIT_COL4_NAME       VARCHAR2(20 BYTE),
  LPIT_COL4_POSITION   NUMBER(5),
  LPIT_COL4_MAPPING    VARCHAR2(50 BYTE),
  LPIT_COL5_NAME       VARCHAR2(20 BYTE),
  LPIT_COL5_POSITION   NUMBER(5),
  LPIT_COL5_MAPPING    VARCHAR2(50 BYTE),
  LPIT_COL6_NAME       VARCHAR2(20 BYTE),
  LPIT_COL6_POSITION   NUMBER(5),
  LPIT_COL6_MAPPING    VARCHAR2(50 BYTE),
  LPIT_COL7_NAME       VARCHAR2(20 BYTE),
  LPIT_COL7_POSITION   NUMBER(5),
  LPIT_COL7_MAPPING    VARCHAR2(50 BYTE),
  LPIT_COL8_NAME       VARCHAR2(20 BYTE),
  LPIT_COL8_POSITION   NUMBER(5),
  LPIT_COL8_MAPPING    VARCHAR2(50 BYTE),
  LPIT_COL9_NAME       VARCHAR2(20 BYTE),
  LPIT_COL9_POSITION   NUMBER(5),
  LPIT_COL9_MAPPING    VARCHAR2(50 BYTE),
  LPIT_COL10_NAME      VARCHAR2(20 BYTE),
  LPIT_COL10_POSITION  NUMBER(5),
  LPIT_COL10_MAPPING   VARCHAR2(50 BYTE),
  LPIT_COL11_NAME      VARCHAR2(20 BYTE),
  LPIT_COL11_POSITION  NUMBER(5),
  LPIT_COL11_MAPPING   VARCHAR2(50 BYTE),
  LPIT_COL12_NAME      VARCHAR2(20 BYTE),
  LPIT_COL12_POSITION  NUMBER(5),
  LPIT_COL12_MAPPING   VARCHAR2(50 BYTE),
  LPIT_COL13_NAME      VARCHAR2(20 BYTE),
  LPIT_COL13_POSITION  NUMBER(5),
  LPIT_COL13_MAPPING   VARCHAR2(50 BYTE),
  LPIT_COL14_NAME      VARCHAR2(20 BYTE),
  LPIT_COL14_POSITION  NUMBER(5),
  LPIT_COL14_MAPPING   VARCHAR2(50 BYTE),
  LPIT_COL15_NAME      VARCHAR2(20 BYTE),
  LPIT_COL15_POSITION  NUMBER(5),
  LPIT_COL15_MAPPING   VARCHAR2(50 BYTE),
  LPIT_COL16_NAME      VARCHAR2(20 BYTE),
  LPIT_COL16_POSITION  NUMBER(5),
  LPIT_COL16_MAPPING   VARCHAR2(50 BYTE),
  LPIT_COL17_NAME      VARCHAR2(20 BYTE),
  LPIT_COL17_POSITION  NUMBER(5),
  LPIT_COL17_MAPPING   VARCHAR2(50 BYTE),
  LPIT_COL18_NAME      VARCHAR2(20 BYTE),
  LPIT_COL18_POSITION  NUMBER(5),
  LPIT_COL18_MAPPING   VARCHAR2(50 BYTE),
  LPIT_COL19_NAME      VARCHAR2(20 BYTE),
  LPIT_COL19_POSITION  NUMBER(5),
  LPIT_COL19_MAPPING   VARCHAR2(50 BYTE),
  LPIT_COL20_NAME      VARCHAR2(20 BYTE),
  LPIT_COL20_POSITION  NUMBER(5),
  LPIT_COL20_MAPPING   VARCHAR2(50 BYTE)
)
TABLESPACE LMSDATA
PCTUSED    40
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX TQ_LMS.LMS_PROD_IMP_TMPLT_PK ON TQ_LMS.LMS_PROD_IMP_TMPLT
(LPIT_CODE)
LOGGING
TABLESPACE LMSDATA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE INDEX TQ_LMS.LPIT_PROD_CODE_IDX ON TQ_LMS.LMS_PROD_IMP_TMPLT
(LPIT_PROD_CODE)
LOGGING
TABLESPACE LMSDATA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


ALTER TABLE TQ_LMS.LMS_PROD_IMP_TMPLT ADD (
  CONSTRAINT LMS_PROD_IMP_TMPLT_PK
  PRIMARY KEY
  (LPIT_CODE)
  USING INDEX TQ_LMS.LMS_PROD_IMP_TMPLT_PK);

ALTER TABLE TQ_LMS.LMS_PROD_IMP_TMPLT ADD (
  CONSTRAINT LMS_PROD_IMP_TMPLT_R01 
  FOREIGN KEY (LPIT_PROD_CODE) 
  REFERENCES TQ_LMS.LMS_PRODUCTS (PROD_CODE));


ALTER TABLE TQ_LMS.LMS_GRP_PREMIUM_RATES
ADD (GPR_SCH_CODE NUMBER(22));

ALTER TABLE TQ_LMS.LMS_COVER_TYPES
ADD (CVT_CLA_CODE NUMBER(15));

ALTER TABLE TQ_LMS.LMS_ANNUITY_TYPES
 DROP PRIMARY KEY CASCADE;

DROP TABLE TQ_LMS.LMS_ANNUITY_TYPES CASCADE CONSTRAINTS;

CREATE TABLE TQ_LMS.LMS_ANNUITY_TYPES
(
  ATY_CODE            NUMBER(15)                NOT NULL,
  ATY_PROD_CODE       NUMBER(15)                NOT NULL,
  ATY_OPTION          VARCHAR2(20 BYTE),
  ATY_GUARANT_PRD     NUMBER(15)                NOT NULL,
  ATY_TYPE            VARCHAR2(100 BYTE)        NOT NULL,
  ATY_RETIREMENT_AGE  NUMBER(8)
)
TABLESPACE LMSDATA
PCTUSED    40
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE INDEX TQ_LMS.ATY_PROD_CODE_IDX ON TQ_LMS.LMS_ANNUITY_TYPES
(ATY_PROD_CODE)
LOGGING
TABLESPACE LMSDATA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE UNIQUE INDEX TQ_LMS.LMS_ANNUITY_TYPES_PK ON TQ_LMS.LMS_ANNUITY_TYPES
(ATY_CODE)
LOGGING
TABLESPACE LMSDATA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE UNIQUE INDEX TQ_LMS.LMS_ANNUITY_TYPES_U01 ON TQ_LMS.LMS_ANNUITY_TYPES
(ATY_GUARANT_PRD, ATY_OPTION, ATY_PROD_CODE, ATY_RETIREMENT_AGE, ATY_TYPE)
LOGGING
TABLESPACE LMSDATA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


DROP PUBLIC SYNONYM LMS_ANNUITY_TYPES;

CREATE OR REPLACE PUBLIC SYNONYM LMS_ANNUITY_TYPES FOR TQ_LMS.LMS_ANNUITY_TYPES;


ALTER TABLE TQ_LMS.LMS_ANNUITY_TYPES ADD (
  CONSTRAINT LMS_ANNUITY_TYPES_PK
  PRIMARY KEY
  (ATY_CODE)
  USING INDEX TQ_LMS.LMS_ANNUITY_TYPES_PK,
  CONSTRAINT LMS_ANNUITY_TYPES_U01
  UNIQUE (ATY_GUARANT_PRD, ATY_OPTION, ATY_PROD_CODE, ATY_RETIREMENT_AGE, ATY_TYPE)
  USING INDEX TQ_LMS.LMS_ANNUITY_TYPES_U01);

ALTER TABLE TQ_LMS.LMS_ANNUITY_TYPES ADD (
  CONSTRAINT ATY_PROD_CODE_FK 
  FOREIGN KEY (ATY_PROD_CODE) 
  REFERENCES TQ_LMS.LMS_PRODUCTS (PROD_CODE));


DROP TABLE TQ_LMS.LMS_RATES_IMPORT_DETAILS CASCADE CONSTRAINTS;

CREATE TABLE TQ_LMS.LMS_RATES_IMPORT_DETAILS
(
  LRID_CODE         NUMBER(22)                  NOT NULL,
  LRID_LRIT_CODE    NUMBER(22),
  LRID_ANB          NUMBER(22),
  LRID_RATE         NUMBER(22,5),
  LRID_SINGLE_RATE  NUMBER(22,5),
  LRID_ANNUAL_RATE  NUMBER(22,5),
  LRID_RATE_DESC    VARCHAR2(20 BYTE),
  LRID_DIV_FACTOR   NUMBER(25,5),
  LRID_WEF          DATE,
  LRID_WET          DATE,
  LRID_SEX          VARCHAR2(1 BYTE)            DEFAULT 'B',
  LRID_ANN_TYPE     VARCHAR2(20 BYTE),
  LRID_GUARN_PRD    NUMBER(22),
  LRID_OPTION       VARCHAR2(20 BYTE),
  LRID_RETIRE_AGE   NUMBER(22),
  LRID_RANGE_FROM   NUMBER(25,5),
  LRID_RANGE_TO     NUMBER(25,5)
)
TABLESPACE LMSDATA
PCTUSED    40
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE INDEX TQ_LMS.LRID_LRIT_CODE_IDX ON TQ_LMS.LMS_RATES_IMPORT_DETAILS
(LRID_LRIT_CODE)
LOGGING
TABLESPACE LMSDATA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


DROP PUBLIC SYNONYM LMS_RATES_IMPORT_DETAILS;

CREATE OR REPLACE PUBLIC SYNONYM LMS_RATES_IMPORT_DETAILS FOR TQ_LMS.LMS_RATES_IMPORT_DETAILS;


ALTER TABLE TQ_LMS.LMS_RATES_IMPORT_DETAILS ADD (
  CONSTRAINT ANN_TYPES
  CHECK (LRID_ANN_TYPE IN ('IMMEDIATE', 'DEFERRED')),
  CONSTRAINT AVAIL_OPTIONS
  CHECK (LRID_OPTION IN ('OPTION 1','OPTION 2',
'OPTION 3', 'OPTION 4', 'OPTION 5')));

ALTER TABLE TQ_LMS.LMS_RATES_IMPORT_DETAILS ADD (
  CONSTRAINT LMS_RATES_IMPORT_DETAILS_R01 
  FOREIGN KEY (LRID_LRIT_CODE) 
  REFERENCES TQ_LMS.LMS_RATES_IMPORT_TRANS (LRIT_CODE));


CREATE SEQUENCE TQ_LMS.LMS_ATY_CODE_SEQ
START WITH 1
INCREMENT BY 1
MINVALUE 1
MAXVALUE 99999999999999999
NOCACHE 
NOCYCLE 
NOORDER 

CREATE SEQUENCE TQ_LMS.LMS_ANNTR_CODE_SEQ
START WITH 1
INCREMENT BY 1
MINVALUE 1
MAXVALUE 99999999999999999
NOCACHE 
NOCYCLE 
NOORDER

CREATE SEQUENCE TQ_LMS.LMS_SCH_CODE_SEQ
START WITH 1
INCREMENT BY 1
MINVALUE 1
MAXVALUE 99999999999999999
NOCACHE 
NOCYCLE 
NOORDER

CREATE SEQUENCE TQ_LMS.LMS_GSUB_CODE_SEQ
START WITH 1
INCREMENT BY 1
MINVALUE 1
MAXVALUE 99999999999999999
NOCACHE 
NOCYCLE 
NOORDER

CREATE SEQUENCE TQ_LMS.LMS_LPIT_CODE_SEQ
START WITH 1
INCREMENT BY 1
MINVALUE 1
MAXVALUE 99999999999999999
NOCACHE 
NOCYCLE 
NOORDER

CREATE SEQUENCE TQ_LMS.LMS_QGSUB_CODE_SEQ
START WITH 1
INCREMENT BY 1
MINVALUE 1
MAXVALUE 99999999999999999
NOCACHE 
NOCYCLE 
NOORDER

CREATE SEQUENCE TQ_LMS.LMS_PGSUB_CODE_SEQ
START WITH 1
INCREMENT BY 1
MINVALUE 1
MAXVALUE 99999999999999999
NOCACHE 
NOCYCLE 
NOORDER

CREATE SEQUENCE TQ_LMS.LMS_LMIS_CODE_SEQ
START WITH 1
INCREMENT BY 1
MINVALUE 1
MAXVALUE 99999999999999999
NOCACHE 
NOCYCLE 
NOORDER






ALTER TABLE TQ_LMS.LMS_SCHOOL_LEVELS
ADD (SLVL_TERM_DURATION NUMBER(15));

ALTER TABLE TQ_LMS.LMS_SCHOOL_LEVELS
ADD (SLVL_NO_TERMS NUMBER(15));

ALTER TABLE TQ_LMS.LMS_SCHOOL_LEVELS
ADD (SLVL_PERIOD NUMBER(15));






ALTER TABLE TQ_LMS.LMS_TREATY_ARRGMT_COMM_RATES
ADD (TACR_MEDICAL VARCHAR2(1 BYTE) DEFAULT 'M');


CREATE TABLE TQ_LMS.LMS_SCHOOL_CLASSES
(
  SCH_CODE       NUMBER,
  SCH_PROD_CODE  NUMBER,
  SCH_SHT_DESC   VARCHAR2(20 BYTE),
  SCH_DESC       VARCHAR2(50 BYTE),
  SCH_PERIOD     NUMBER(22),
  SCH_SLVL_CODE  NUMBER(22)
)
TABLESPACE LMSDATA
PCTUSED    40
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX TQ_LMS.LMS_SCHOOL_CLASSES_PK ON TQ_LMS.LMS_SCHOOL_CLASSES
(SCH_CODE)
LOGGING
TABLESPACE LMSDATA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE UNIQUE INDEX TQ_LMS.LMS_SCH_SHT_DESC_UNQ ON TQ_LMS.LMS_SCHOOL_CLASSES
(SCH_SHT_DESC)
LOGGING
TABLESPACE LMSDATA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE INDEX TQ_LMS.SCH_PROD_CODE_IDX ON TQ_LMS.LMS_SCHOOL_CLASSES
(SCH_PROD_CODE)
LOGGING
TABLESPACE LMSDATA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE INDEX TQ_LMS.SCH_SLVL_CODE_IDX ON TQ_LMS.LMS_SCHOOL_CLASSES
(SCH_SLVL_CODE)
LOGGING
TABLESPACE LMSDATA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;

CREATE OR REPLACE PUBLIC SYNONYM LMS_SCHOOL_CLASSES FOR TQ_LMS.LMS_SCHOOL_CLASSES;


ALTER TABLE TQ_LMS.LMS_SCHOOL_CLASSES ADD (
  CONSTRAINT LMS_SCHOOL_CLASSES_PK
  PRIMARY KEY
  (SCH_CODE)
  USING INDEX TQ_LMS.LMS_SCHOOL_CLASSES_PK,
  CONSTRAINT LMS_SCH_SHT_DESC_UNQ
  UNIQUE (SCH_SHT_DESC)
  USING INDEX TQ_LMS.LMS_SCH_SHT_DESC_UNQ);

ALTER TABLE TQ_LMS.LMS_SCHOOL_CLASSES ADD (
  CONSTRAINT LMS_SLVL_CODE_FK 
  FOREIGN KEY (SCH_SLVL_CODE) 
  REFERENCES TQ_LMS.LMS_SCHOOL_LEVELS (SLVL_CODE),
  FOREIGN KEY (SCH_PROD_CODE) 
  REFERENCES TQ_LMS.LMS_PRODUCTS (PROD_CODE));


CREATE OR REPLACE TYPE TQ_LMS.LMS_POLICIES_MEM_LOADING AS OBJECT (
LGMD_SN              NUMBER(15), 
LGMD_SURNAME         VARCHAR2(100), 
LGMD_DOB             DATE,
LGMD_ANB             NUMBER(15), 
LGMD_BASIC           VARCHAR2(100), 
LGMD_HOUSING         VARCHAR2(100), 
LGMD_TRANSPORT       VARCHAR2(100), 
LGMD_MONTH_SAL       VARCHAR2(100),
LGMD_TOT_EMUL        NUMBER(15), 
LGMD_SA              NUMBER(15), 
LGMD_PREM            NUMBER(15),  
LGMD_PREM_RATE       NUMBER(15),  
LGMD_DOJ             DATE,
LGMD_COVER_FROM_DATE DATE
   );
   
CREATE OR REPLACE TYPE TQ_LMS.LMS_POLICIES_MEM_LOADING_TAB  AS TABLE OF LMS_POLICIES_MEM_LOADING;

CREATE OR REPLACE TYPE TQ_LMS.LMS_GRP_MEM_SDIV_IMPORT AS OBJECT (
      LMIS_LMIT_CODE           NUMBER(22),
      LMIS_LMID_CODE           NUMBER(22),
      LMIS_GSUB_CODE           NUMBER(22),         
      LMIS_GSUB_SHT_DESC       VARCHAR2(50),
      SDPARAMETER_VALS         VARCHAR2(200)
   );
   
CREATE OR REPLACE TYPE TQ_LMS.LMS_GRP_MEM_SDIV_IMPORT_TAB  AS TABLE OF LMS_GRP_MEM_SDIV_IMPORT;


CREATE OR REPLACE TYPE TQ_LMS.LMS_GRP_MEM_IMPORT AS OBJECT (
      LMID_LMIT_CODE           NUMBER(15),
      PARAMETER_VALS           VARCHAR2(4000)
   );
   
CREATE OR REPLACE TYPE TQ_LMS.LMS_GRP_MEM_IMPORT_TAB  AS TABLE OF LMS_GRP_MEM_IMPORT;

CREATE TABLE TQ_LMS.LMS_MEMBER_IMPORT_SUBDIV
(
  LMIS_CODE           NUMBER(22),
  LMIS_LMIT_CODE      NUMBER(22),
  LMIS_LMID_CODE      NUMBER(22),
  LMIS_GSUB_CODE      NUMBER(22),
  LMIS_GSUB_SHT_DESC  VARCHAR2(50 BYTE),
  LMIS_VALUE          VARCHAR2(200 BYTE)
)
TABLESPACE LMSDATA
PCTUSED    40
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE INDEX TQ_LMS.LMIS_LMID_CODE_IDX ON TQ_LMS.LMS_MEMBER_IMPORT_SUBDIV
(LMIS_LMID_CODE)
LOGGING
TABLESPACE LMSDATA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE UNIQUE INDEX TQ_LMS.LMS_MEMBER_IMPORT_SUBDIV_PK ON TQ_LMS.LMS_MEMBER_IMPORT_SUBDIV
(LMIS_CODE)
LOGGING
TABLESPACE LMSDATA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


ALTER TABLE TQ_LMS.LMS_MEMBER_IMPORT_SUBDIV ADD (
  CONSTRAINT LMS_MEMBER_IMPORT_SUBDIV_PK
  PRIMARY KEY
  (LMIS_CODE)
  USING INDEX TQ_LMS.LMS_MEMBER_IMPORT_SUBDIV_PK);

ALTER TABLE TQ_LMS.LMS_MEMBER_IMPORT_SUBDIV ADD (
  CONSTRAINT LMS_MEMBER_IMPORT_SUBDIV_R01 
  FOREIGN KEY (LMIS_LMID_CODE) 
  REFERENCES TQ_LMS.LMS_MEMBER_IMPORT_DETAILS (LMID_CODE));







