 
ALTER TYPE LMS_POLICIES_LOADING
ADD ATTRIBUTE (LGPL_PENS_COMM_RATE VARCHAR2(20))
CASCADE


 ALTER TYPE LMS_POLICIES_LOADING
ADD
 ATTRIBUTE (LGPL_PENS_PAYMENT_FREQ VARCHAR2(100),
 LGPL_REGISTERED VARCHAR2(100),
 LGPL_REG_NO VARCHAR2(100),
 LGPL_PENS_TYPE VARCHAR2(100),
 LGPL_CONTRI_TYPE VARCHAR2(100),
 LGPL_EMYE_CONTRI VARCHAR2(100),
LGPL_EMYR_CONTRI VARCHAR2(100),
LGPL_MALE_NRD VARCHAR2(3),
LGPL_FEMALE_NRD VARCHAR2(3),
LGPL_GRNTD_PRD  VARCHAR2(10),
LGPL_EARNINGS_ESC VARCHAR2(100)
)
CASCADE; 

ALTER TYPE LMS_POLICIES_LOADING COMPILE;

