 CREATE TABLE LMS_PENSION_TRUSTEES ( 
    LPT_CODE NUMBER,
    LPT_STATUS VARCHAR2(100 BYTE), 
    LPT_REPRESENTATION VARCHAR2(100 BYTE),
    LPT_TEL_NO VARCHAR2(100 BYTE),
    LPT_PIN_NO VARCHAR2(100 BYTE), 
    LPT_ID_NO VARCHAR2(100 BYTE),
    LPT_CERT_NO VARCHAR2(100 BYTE), 
    LPT_WEF_DATE DATE, 
    LPT_WET_DATE DATE,
    LPT_REN_DATE DATE,
    LPT_ADDRESS VARCHAR2(100 BYTE), 
    LPT_ENDR_CODE NUMBER, 
    LPT_SURNAME VARCHAR2(100 BYTE),
    LPT_OTHER_NAMES VARCHAR2(100 BYTE) 
    ) ;
