SET DEFINE OFF;
Insert into TQC_SYS_PROCESSES
   (SPRC_CODE, SPRC_SYS_CODE, SPRC_PROCESS, SPRC_BPM_ID, SPRC_SHT_DESC, 
    SPRC_JPDL_DESC)
 Values
   (723, 27, 'GROUP PENSIONS PROCESS', NULL, 'GLPNS', 
    'EndorsementsProcess');
COMMIT;

SET DEFINE OFF;
Insert into TQC_SYS_PROCESS_AREAS
   (SPRCA_CODE, SPRCA_SPRC_CODE, SPRCA_AREA, SPRCA_SHT_DESC)
 Values
   (1478, 723, 'GROUP VALUATION PROCESS', 'GLVAL');
COMMIT;


SET DEFINE OFF;
Insert into TQC_SYS_PROCESS_SUB_AREAS
   (SPRSA_CODE, SPRSA_SPRCA_CODE, SPRSA_SPRC_CODE, SPRSA_SUB_AREA, SPRSA_TYPE, 
    SPRSA_SHT_DESC, SPRSA_DEFAULT_USR_CODE)
 Values
   (1780, 1478, 723, 'GROUP VALUATION ACCESS', 'C', 
    'ACCS', NULL);
Insert into TQC_SYS_PROCESS_SUB_AREAS
   (SPRSA_CODE, SPRSA_SPRCA_CODE, SPRSA_SPRC_CODE, SPRSA_SUB_AREA, SPRSA_TYPE, 
    SPRSA_SHT_DESC, SPRSA_DEFAULT_USR_CODE)
 Values
   (1781, 1478, 723, 'GROUP VALUATION PROCESSING', 'A', 
    'VLPR', NULL);
Insert into TQC_SYS_PROCESS_SUB_AREAS
   (SPRSA_CODE, SPRSA_SPRCA_CODE, SPRSA_SPRC_CODE, SPRSA_SUB_AREA, SPRSA_TYPE, 
    SPRSA_SHT_DESC, SPRSA_DEFAULT_USR_CODE)
 Values
   (1782, 1478, 723, 'RE-VALUATION ACCESS', 'C', 
    'VLRE', NULL);
COMMIT;
