DROP TYPE LMS_RECEIPT_COMM_TAB;

DROP TYPE LMS_RECEIPT_COMM;

CREATE OR REPLACE TYPE  "LMS_RECEIPT_COMM" AS OBJECT (
      GRCT_CODE           NUMBER(15),
      TRANS_CODE          NUMBER(15),
      PCP_CODE            NUMBER(15),
      CCL_CODE            NUMBER(15)   
   );
   
CREATE OR REPLACE TYPE "LMS_RECEIPT_COMM_TAB" AS TABLE OF LMS_RECEIPT_COMM; 