SET DEFINE OFF;
Insert into TQC_SYS_PROCESSES
   (SPRC_CODE, SPRC_SYS_CODE, SPRC_PROCESS, SPRC_BPM_ID, SPRC_SHT_DESC, 
    SPRC_JPDL_DESC)
 Values
   (681, 27, 'CHANGE OF LIFE FACTOR', NULL, 'UWCL', 
    'EndorsementsProcess');
COMMIT;
SET DEFINE OFF;
Insert into TQC_SYS_PROCESS_AREAS
   (SPRCA_CODE, SPRCA_SPRC_CODE, SPRCA_AREA, SPRCA_SHT_DESC)
 Values
   (1470, 681, 'CHANGE LIFE FACTOR ACCESS', 'ACCS');
Insert into TQC_SYS_PROCESS_AREAS
   (SPRCA_CODE, SPRCA_SPRC_CODE, SPRCA_AREA, SPRCA_SHT_DESC)
 Values
   (1471, 681, 'CHANGE LIFE FACTOR UNDEWRITING', 'DENTR');
Insert into TQC_SYS_PROCESS_AREAS
   (SPRCA_CODE, SPRCA_SPRC_CODE, SPRCA_AREA, SPRCA_SHT_DESC)
 Values
   (1472, 681, 'CHANGE LIFE FACTOR UNDEWRITING', 'CLUW');
Insert into TQC_SYS_PROCESS_AREAS
   (SPRCA_CODE, SPRCA_SPRC_CODE, SPRCA_AREA, SPRCA_SHT_DESC)
 Values
   (1473, 681, 'CHANGE LIFE FACTOR DISPATCH', 'EDISP');
COMMIT;
SET DEFINE OFF;
Insert into TQC_SYS_PROCESS_SUB_AREAS
   (SPRSA_CODE, SPRSA_SPRCA_CODE, SPRSA_SPRC_CODE, SPRSA_SUB_AREA, SPRSA_TYPE, 
    SPRSA_SHT_DESC, SPRSA_DEFAULT_USR_CODE)
 Values
   (1742, 1470, 681, 'CHANGE LIFE FACTOR ACCESS', 'C', 
    'ACCS', NULL);
Insert into TQC_SYS_PROCESS_SUB_AREAS
   (SPRSA_CODE, SPRSA_SPRCA_CODE, SPRSA_SPRC_CODE, SPRSA_SUB_AREA, SPRSA_TYPE, 
    SPRSA_SHT_DESC, SPRSA_DEFAULT_USR_CODE)
 Values
   (1743, 1471, 681, 'CHANGE LIFE FACTOR DETAILS', 'C', 
    'CLDAT', NULL);
Insert into TQC_SYS_PROCESS_SUB_AREAS
   (SPRSA_CODE, SPRSA_SPRCA_CODE, SPRSA_SPRC_CODE, SPRSA_SUB_AREA, SPRSA_TYPE, 
    SPRSA_SHT_DESC, SPRSA_DEFAULT_USR_CODE)
 Values
   (1744, 1472, 681, 'CL UW PROCESSING', 'C', 
    'CLUW', NULL);
Insert into TQC_SYS_PROCESS_SUB_AREAS
   (SPRSA_CODE, SPRSA_SPRCA_CODE, SPRSA_SPRC_CODE, SPRSA_SUB_AREA, SPRSA_TYPE, 
    SPRSA_SHT_DESC, SPRSA_DEFAULT_USR_CODE)
 Values
   (1745, 1472, 681, 'CL UW MAKE READY', 'A', 
    'CLMR', NULL);
Insert into TQC_SYS_PROCESS_SUB_AREAS
   (SPRSA_CODE, SPRSA_SPRCA_CODE, SPRSA_SPRC_CODE, SPRSA_SUB_AREA, SPRSA_TYPE, 
    SPRSA_SHT_DESC, SPRSA_DEFAULT_USR_CODE)
 Values
   (1746, 1472, 681, 'CL AUTHORIZATION', 'A', 
    'CLAU', NULL);
Insert into TQC_SYS_PROCESS_SUB_AREAS
   (SPRSA_CODE, SPRSA_SPRCA_CODE, SPRSA_SPRC_CODE, SPRSA_SUB_AREA, SPRSA_TYPE, 
    SPRSA_SHT_DESC, SPRSA_DEFAULT_USR_CODE)
 Values
   (1747, 1473, 681, 'POLICY DOCUMENTS DISPATCH', 'C', 
    'EDISP', NULL);
COMMIT;

SET DEFINE OFF;
Insert into LMS_BUSINESS_TRANSACTIONS
   (BTR_TRANS_CODE, BTR_TRANS_TYPE, BTR_DEBIT_CODE, BTR_CREDIT_CODE, BTR_CLM_UW, 
    BTR_WEB_GROUPING)
 Values
   ('CL', 'CHANGE OF LIFE FACTOR', 'CLD', 'CLC', 'U', 
    NULL);
COMMIT;
