ALTER TABLE TQ_LMS.LMS_PRODUCTS
ADD (PROD_FCL_SA_FORMULA VARCHAR2(1 BYTE) DEFAULT 'T');

COMMENT ON COLUMN 
TQ_LMS.LMS_PRODUCTS.PROD_FCL_SA_FORMULA IS 
'STORES THE FCL SA FORMULA T FOR TOTAL SA. A FOR SA ABOVE FCL';
