BEGIN
Insert into TQC_SYSTEM_REPORTS
   (RPT_CODE, RPT_SYS_CODE, RPT_NAME, RPT_DESCRIPTION, RPT_DATA_FILE, 
    RPT_APPLCTN_LEVEL, RPT_ACTIVE)
 Values
   (2289, 27, 'WITHDRAWAL_MEM_STAT', 'WITHDRAWAL_MEM_STAT_RPT', 'clm_mem_stat.xml', 
    NULL, 'A');
Insert into TQC_SYS_RPT_TEMPLATES
   (RPT_TMPL_CODE, RPT_TMPL_RPT_CODE, RPT_TMPL_FILE, RPT_TMPL_NAME, RPT_TMPL_DESCRIPTION, 
    RPT_TMPL_STYLE_FILE, RPT_TMPL_ORG_CODE, RPT_TMPL_ACTIVE)
 Values
   (3626, 2289, 'clm_mem_stat_temp.rtf', 'WITHDRAWAL_MEM_STAT', 'Withdrwawal Member Statemnt Template', 
    'clm_mem_stat_temp.xsl', NULL, 'A');
COMMIT;
END;
/