begin
Insert into LMS_AGENCIES
   (AGN_CODE, AGN_ACT_CODE, AGN_SHT_DESC, AGN_NAME, AGN_PHYSICAL_ADDRESS, 
    AGN_POSTAL_ADDRESS, AGN_TWN_CODE, AGN_COU_CODE, AGN_EMAIL_ADDRESS, AGN_WEB_ADDRESS, 
    AGN_ZIP, AGN_CONTACT_PERSON, AGN_CONTACT_TITLE, AGN_TEL1, AGN_TEL2, 
    AGN_FAX, AGN_ACC_NO, AGN_PIN, AGN_AGENT_COMMISSION, AGN_CREDIT_ALLOWED, 
    AGN_AGENT_WHT_TAX, AGN_PRINT_DBNOTE, AGN_STATUS, AGN_DATE_CREATED, AGN_CREATED_BY, 
    AGN_REG_CODE, AGN_COMM_RESERVE_RATE, AGN_ANNUAL_BUDGET, AGN_STATUS_EFF_DATE, AGN_CREDIT_PERIOD, 
    AGN_COMM_STATUS_DT, AGN_COMM_ALLOWED, AGN_CHECKED, AGN_CHECKED_BY, AGN_CHECK_DATE, 
    AGN_COMP_COMM_ARREARS, AGN_REINSURER, AGN_COMM_STAT_EFF_DT, AGN_ID_NO, AGN_BRN_CODE, 
    AGN_PHOTO, AGN_REG_STATUS, AGN_SIGNATURE, AGN_REG_NUMBER, AGN_BRU_CODE, 
    AGN_PROFICIENCY_CERT_NO, AGN_CONTRACTED, AGN_UNIT_MGR, AGN_CONTRACT_DATE, AGN_DATE_JOINED, 
    AGN_DATE_TERMINATED, AGN_BANK_ACC_NO, AGN_BANK, AGN_COMM_PAYABLE, AGN_COMM_PYMT_MTHD, 
    AGN_SMS_TEL, AGN_ATR_CODE, AGN_BBR_CODE, AGN_PHONE_NO, AGN_PIN_NO, 
    AGN_WHT_TAX, AGN_REF_NO, AGN_POST_LEVEL, AGN_COIN_GL_CODE, AGN_OSD_CODE, 
    AGN_COMM_PERC_PYBLE, AGN_SUB_STATUS, AGN_SUB_STATUS_DATE, AGN_CAP_EXEMPTED, AGN_PYRLL_SEQNO, 
    AGN_BANK_ACC_NAME, AGN_BIRTH_DATE, AGN_COP_COMPLIANT)
 Values
   (0, 1, 'DIRECT', 'DIRECT', NULL, 
    NULL, NULL, NULL, NULL, NULL, 
    NULL, NULL, NULL, NULL, NULL, 
    NULL, NULL, NULL, NULL, NULL, 
    NULL, 'Y', 'ACTIVE', NULL, NULL, 
    NULL, NULL, NULL, NULL, NULL, 
    NULL, NULL, NULL, NULL, NULL, 
    NULL, NULL, NULL, NULL, NULL, 
    NULL, NULL, NULL, NULL, NULL, 
    NULL, NULL, 'N', NULL, NULL, 
    NULL, NULL, NULL, 'Y', 'NORM', 
    NULL, NULL, NULL, NULL, NULL, 
    NULL, NULL, NULL, NULL, NULL, 
    NULL, NULL, NULL, 'N', NULL, 
    NULL, NULL, NULL);
end;
/