BEGIN
Insert into TQC_SYSTEM_REPORTS
   (RPT_CODE, RPT_SYS_CODE, RPT_NAME, RPT_DESCRIPTION, RPT_DATA_FILE, 
    RPT_APPLCTN_LEVEL, RPT_ACTIVE)
 Values
   (2090, 27, 'GL_SUMMARY', 'Group Life Summary Report', 'gl_sum.xml', 
    NULL, 'A');
Insert into TQC_SYS_RPT_TEMPLATES
   (RPT_TMPL_CODE, RPT_TMPL_RPT_CODE, RPT_TMPL_FILE, RPT_TMPL_NAME, RPT_TMPL_DESCRIPTION, 
    RPT_TMPL_STYLE_FILE, RPT_TMPL_ORG_CODE, RPT_TMPL_ACTIVE)
 Values
   (3410, 2090, 'gl_sum_temp.rtf', 'GL_SUMMARY_RPT', 'Group Life Summary Report', 
    'gl_sum_temp.xsl', NULL, 'A');
        Insert into TQC_SYS_RPT_PARAMETERS
       (RPTP_CODE, RPTP_RPT_CODE, RPTP_PARAM_NAME, RPTP_PARAM_DESC, RPTP_PARAM_PROMPT, 
        RPTP_PARAM_TYPE, RPTP_PARENT_CODE, RPTP_QUERY, RPTP_PARAM_CLAUSE, RPTP_USER_REQUIRED, 
        RPTP_CHILD_CODE, RPTP_PARAM_ACTIVE)
        Values
       (24925, 2090, 'END_DATE', 'END DATE', 'END Date', 
        'DATE', NULL, NULL, NULL, NULL, 
        NULL, 'A');
    Insert into TQC_SYS_RPT_PARAMETERS
       (RPTP_CODE, RPTP_RPT_CODE, RPTP_PARAM_NAME, RPTP_PARAM_DESC, RPTP_PARAM_PROMPT, 
        RPTP_PARAM_TYPE, RPTP_PARENT_CODE, RPTP_QUERY, RPTP_PARAM_CLAUSE, RPTP_USER_REQUIRED, 
        RPTP_CHILD_CODE, RPTP_PARAM_ACTIVE)
       Values
       (24924, 2090, 'START_DATE', 'START DATE', 'Start Date', 
        'DATE', NULL, NULL, NULL, NULL, 
        NULL, 'A');
COMMIT;
END;
/
