ALTER TABLE TQ_LMS.LMS_QCVT_DEPENDENT_LIMITS
ADD (QDL_MIN_AMT NUMBER(22,5))

COMMENT ON COLUMN 
TQ_LMS.LMS_QCVT_DEPENDENT_LIMITS.QDL_MIN_AMT IS 
'THIS IS THE MINIMUM AMOUNT THE COVER DEPENDENT LIMIT IS ALLOWED';

ALTER TABLE TQ_LMS.LMS_POL_DEPENDENT_LIMITS
ADD (PDL_MIN_AMT NUMBER(22,5))

COMMENT ON COLUMN 
TQ_LMS.LMS_POL_DEPENDENT_LIMITS.PDL_MIN_AMT IS 
'THIS IS THE MINIMUM AMOUNT ALLOWED ON THE COVER DEPENDENT LIMIT';


ALTER TABLE TQ_LMS.lms_ren_pol_depend_limits
ADD (PDL_MIN_AMT NUMBER(22,5))

COMMENT ON COLUMN 
TQ_LMS.lms_ren_pol_depend_limits.PDL_MIN_AMT IS 
'THIS IS THE MINIMUM AMOUNT ALLOWED ON THE COVER DEPENDENT LIMIT';
