ALTER TABLE TQ_LMS.LMS_POLICY_MEMBERS_ANB
ADD (POLMA_CERT_NO VARCHAR2(50 BYTE));


------------------------------------
SET DEFINE OFF;
Insert into TQ_LMS.LMS_PARAMETERS
   (PARAM_CODE, PARAM_NAME, PARAM_VALUE, PARAM_STATUS, PARAM_DESC, PARAM_PROD_SPECIFIC, PARAM_CLA_TYPE)
 Values
   (2012139, 'GEN_MEMBER_CERT_NO', 'N', 'A', 'IF Y GENERATE MEMBER CERTIFICATE NUMBER ELSE LEAVE OUT CERFICATE NO GENERATION', 
    'N', 'G');
COMMIT;
------------------------------------------------------------------------------------------------
CREATE SEQUENCE LMS_CERT_NO_SEQ 
START WITH 1 
MAXVALUE 999999999 
MINVALUE 1;