--creates a column to hold the rate type--

ALTER TABLE TQ_LMS.LMS_PRODUCTS
ADD (PROD_RATE_TYPE VARCHAR2(1 BYTE));
----
ALTER TABLE TQ_LMS.LMS_PROD_COVER_TYPES
ADD (PCT_EM NUMBER)

COMMENT ON COLUMN 
TQ_LMS.LMS_PROD_COVER_TYPES.PCT_EM IS 
'COVER ERROR MARGIN';
----
ALTER TABLE TQ_LMS.LMS_PROD_COVER_TYPES
ADD (PCT_PROFIT_MARGIN NUMBER);

COMMENT ON COLUMN 
TQ_LMS.LMS_PROD_COVER_TYPES.PCT_PROFIT_MARGIN IS 
'COVER PROFIT MARGIN';
----
ALTER TABLE LMS_POLICY_COVER_TYPES
ADD (PCT_MNGT_EXPENSES NUMBER);

ALTER TABLE LMS_POLICY_COVER_TYPES
ADD (PCT_PHCF NUMBER);
----
ALTER TABLE TQ_LMS.LMS_PROD_COVER_TYPES
ADD (PCT_ADR_RATE NUMBER);

---
ALTER TABLE TQ_LMS.LMS_PROD_COVER_TYPES
ADD (PCT_ADR_RATE_DIV_FACT NUMBER);

COMMENT ON COLUMN 
TQ_LMS.LMS_PROD_COVER_TYPES.PCT_ADR_RATE_DIV_FACT IS 
'ADR DIVISION FACTOR';


COMMENT ON COLUMN 
TQ_LMS.LMS_PROD_COVER_TYPES.PCT_ADR_RATE IS 
'ACCIDENTAL DEATH RATE';
----
LMS_SETUPS_CURSOR
LMS_SETUPS_PKG
----

ALTER TABLE TQ_LMS.LMS_GRP_PREMIUM_RATES
ADD (GPR_PURE_RATE NUMBER)

COMMENT ON COLUMN 
TQ_LMS.LMS_GRP_PREMIUM_RATES.GPR_PURE_RATE IS 
'pure rate';
----
ALTER TABLE TQ_LMS.LMS_GRP_PREMIUM_RATES
ADD (GPR_PURE_ANNUAL_RATE NUMBER);

----
ALTER TABLE TQ_LMS.LMS_GRP_PREMIUM_RATES
ADD (GPR_PURE_SINGLE_RATE NUMBER);
----
ALTER TABLE TQ_LMS.LMS_PROD_COVER_TYPES
ADD (PCT_MED_COST NUMBER);

----
ALTER TABLE TQ_LMS.LMS_PROD_COVER_TYPES
ADD (PCT_STAMP_DUTY NUMBER);
----
ALTER TABLE TQ_LMS.LMS_PROD_COVER_TYPES
ADD (PCT_COMM_RATE NUMBER);


ALTER TABLE TQ_LMS.LMS_QUOT_MEMBER_CVT
ADD (QCM_PURE_RATE NUMBER);

ALTER TABLE TQ_LMS.LMS_QUOT_MEMBER_CVT
ADD (QCM_PURE_PREMIUM NUMBER);

ALTER TABLE TQ_LMS.LMS_QUOT_MEMBER_CVT
ADD (QCM_ADR_RATE NUMBER);

ALTER TABLE TQ_LMS.LMS_QUOT_MEMBER_CVT
ADD (QCM_ACCIDENTAL_PREM NUMBER);
----
ALTER TABLE TQ_LMS.LMS_POLICY_MEMBER_COVERS
ADD (PCM_PURE_RATE NUMBER);

ALTER TABLE TQ_LMS.LMS_POLICY_MEMBER_COVERS
ADD (PCM_PURE_PREMIUM NUMBER);
----
ALTER TABLE TQ_LMS.LMS_POLICY_MEMBER_COVERS
ADD (PCM_ADR_RATE NUMBER);

ALTER TABLE TQ_LMS.LMS_POLICY_MEMBER_COVERS
ADD (PCM_ACCIDENTAL_PREM NUMBER);

