CREATE TABLE LMS_MULTIPLE_CLAIMS
(
MCLM_CODE NUMBER,
MCLM_MEM_NO VARCHAR2(50),
MCLM_POLM_CODE NUMBER,
MCLM_MIN_INFO_PROVIDED VARCHAR2(1),
MCLM_CAUS_CODE NUMBER,
MCLM_DDC_CODE NUMBER,
MCLM_DEATH_DISABILITY_LOC VARCHAR2(100),
MCLM_DATE_DEATH_ACCIDENT DATE,
MCLM_DATE_CLAIM_REPORTED DATE,
MCLM_DEATH_LOCATION DATE,
MCLM_POL_CODE  NUMBER,
PRIMARY KEY(MCLM_CODE)
)






CREATE SEQUENCE  LMS_MCLM_CODE_SEQ
START WITH 1
INCREMENT BY 1
MAXVALUE 99999999999