package LMSG.view.Base;

import java.math.BigDecimal;
import javax.faces.context.ExternalContext;
import javax.faces.context.FacesContext;
import javax.servlet.http.HttpSession;

public class ReinitializeVar
{
  HttpSession session = (HttpSession)FacesContext.getCurrentInstance().getExternalContext().getSession(false);
  
  public void ReinitializeVariables()
  {
    this.session.removeAttribute("GrctReceiptNo");
    this.session.removeAttribute("GrctPensAlloc");
    this.session.removeAttribute("GrctPremAlloc");
    this.session.removeAttribute("EndorseRIAuth");
    this.session.setAttribute("limitExceeded", "N");
    this.session.setAttribute("ProductCommCvrParam", "N");
    this.session.setAttribute("ImportlimitExceeded", "N");
    this.session.removeAttribute("srchMemName");
    this.session.removeAttribute("srchMemNo");
    this.session.removeAttribute("sbuCode");
    this.session.removeAttribute("spokeCode");
    this.session.removeAttribute("coverageAreaCode");
    this.session.removeAttribute("locationCode");
    
    this.session.setAttribute("calcType", "D");
    this.session.setAttribute("TicketModule", "P");
    this.session.removeAttribute("PolicydivisionCode");
    this.session.removeAttribute("rptLCACode");
    this.session.removeAttribute("QuotedivisionCode");
    this.session.removeAttribute("subdivisionCode");
    this.session.removeAttribute("umbrellaDurationType");
    this.session.setAttribute("umbrellaCover", "N");
    this.session.setAttribute("disableDurationSel", "N");
    this.session.removeAttribute("lpagDesc");
    this.session.removeAttribute("catlpagCode");
    this.session.removeAttribute("lpagPolicyCode");
    this.session.removeAttribute("lpagCode");
    this.session.removeAttribute("JointagnCode");
    this.session.removeAttribute("jointAgentCode");
    this.session.removeAttribute("categoryMaskCode");
    this.session.removeAttribute("coverMaskCode");
    this.session.removeAttribute("cloneProdCode");
    this.session.setAttribute("allCovers", "N");
    this.session.setAttribute("importstate", "A");
    this.session.setAttribute("TotalMembers", new BigDecimal("0"));
    this.session.setAttribute("ValidMembers", new BigDecimal("0"));
    this.session.setAttribute("InValidMembers", new BigDecimal("0"));
    this.session.setAttribute("depCovered", "S");
    this.session.removeAttribute("monthValue");
    this.session.removeAttribute("endrType");
    this.session.removeAttribute("mktCode");
    this.session.removeAttribute("mktShtDesc");
    this.session.setAttribute("exclQuotes", "NONE");
    this.session.setAttribute("allocationType", "ND");
    this.session.setAttribute("coinsLevel", "P");
    this.session.setAttribute("RenewalArea", "N");
    this.session.setAttribute("prodSpecific", "N");
    this.session.removeAttribute("pdedCode");
    this.session.removeAttribute("pcyCode");
    this.session.removeAttribute("pgvsCode");
    this.session.setAttribute("booleanSelect", "F");
    this.session.setAttribute("loadedPolEndorsement", "N");
    this.session.removeAttribute("pcfrCode");
    this.session.removeAttribute("agnNameSearch");
    this.session.setAttribute("receiptTemplateSeq", Integer.valueOf(0));
    this.session.removeAttribute("govtAuthCode");
    this.session.removeAttribute("gagnCode");
    this.session.removeAttribute("qabCode");
    this.session.removeAttribute("pabCode");
    this.session.removeAttribute("productType");
    this.session.removeAttribute("scheduleNo");
    this.session.removeAttribute("pensionPayee");
    this.session.removeAttribute("craRefNo");
    this.session.removeAttribute("craAmount");
    this.session.removeAttribute("CRAMTRANCODE");
    this.session.setAttribute("benModule", "P");
    this.session.removeAttribute("CoinsLeadFollow");
    this.session.removeAttribute("rptProductCode");
    this.session.removeAttribute("CoinsPolicy");
    this.session.removeAttribute("withdrawalReceipt");
    this.session.removeAttribute("pensTransType");
    this.session.removeAttribute("reinsPmasCode");
    this.session.removeAttribute("rateAmt");
    this.session.setAttribute("RIProcessing", "N");
    this.session.removeAttribute("gblCode");
    this.session.removeAttribute("CTL_CODE");
    this.session.removeAttribute("CTL_QUO_LCA_CODE");
    this.session.removeAttribute("pendingClaim");
    this.session.setAttribute("editComponents", "N");
    this.session.removeAttribute("callScreen");
    this.session.removeAttribute("delExistMembers");
    this.session.removeAttribute("endrValue");
    this.session.removeAttribute("PNDP_CODE");
    this.session.removeAttribute("reusePolCode");
    this.session.setAttribute("coversAvail", "N");
    this.session.removeAttribute("ProductCode");
    this.session.removeAttribute("EndorsementStatus");
    this.session.setAttribute("taxtypeAppl", "Y");
    this.session.setAttribute("facPlacements", "N");
    this.session.removeAttribute("studentBenCode");
    this.session.removeAttribute("QuoteCategoryShtDesc");
    this.session.removeAttribute("ClassSchLevel");
    this.session.removeAttribute("schLevel");
    this.session.removeAttribute("VoucherDecision");
    this.session.removeAttribute("ValuationPeriod");
    this.session.removeAttribute("newWETDate");
    this.session.removeAttribute("schCode");
    this.session.removeAttribute("PolicyCoverType");
    this.session.removeAttribute("PolicyCategory");
    this.session.removeAttribute("PolicyDependants");
    this.session.removeAttribute("DepTypeCode");
    this.session.removeAttribute("DepTypeDesc");
    this.session.removeAttribute("prpCode");
    this.session.removeAttribute("ta_code");
    this.session.removeAttribute("OccupationCode");
    this.session.removeAttribute("TaxesCode");
    this.session.removeAttribute("MemberNumber");
    this.session.removeAttribute("MemberNumber1");
    this.session.removeAttribute("EffectiveDate");
    LOVCC.FCLEndorsNo = null;
    LOVCC.CoverFromDate = null;
    LOVCC.CoverToDate = null;
    
    this.session.removeAttribute("ClaimTransactionType");
    
    this.session.removeAttribute("qcvtCode");
    this.session.removeAttribute("QuoteCode");
    
    this.session.removeAttribute("CurrentStatus");
    this.session.removeAttribute("ProductLapsationDays");
    this.session.removeAttribute("LapseType");
    this.session.removeAttribute("CMLCode");
    this.session.removeAttribute("PaymentsFlag");
    this.session.removeAttribute("MedPolicy");
    this.session.removeAttribute("MedTransNo");
    this.session.removeAttribute("CMICode");
    this.session.removeAttribute("MedicalScrnRender");
    

    this.session.removeAttribute("sysModule");
    this.session.removeAttribute("msgType");
    this.session.removeAttribute("msgTempCode");
    this.session.removeAttribute("msgTempShtDesc");
    this.session.removeAttribute("msgTempDesc");
    this.session.removeAttribute("smsCode");
    this.session.removeAttribute("AgentCode");
    LOVCC.TransactionNumber = null;
    
    this.session.removeAttribute("UWYear");
    LOVCC.DeductionCode = null;
    LOVCC.PDED_CODE = null;
    LOVCC.Allocated = null;
    this.session.removeAttribute("townCode");
    this.session.removeAttribute("countryCode");
    this.session.removeAttribute("sectorCode");
    this.session.removeAttribute("branchCode");
    this.session.removeAttribute("postalZIPCode");
    this.session.removeAttribute("domicileCountry");
    this.session.removeAttribute("occupationlifeClass");
    
    LOVCC.enquiryMode = false;
    LOVCC.clientexists = false;
    
    this.session.setAttribute("ScreenPosition", Integer.valueOf(0));
    
    this.session.removeAttribute("prpCode");
    this.session.removeAttribute("prpDesc");
    this.session.removeAttribute("gcoCode");
    this.session.removeAttribute("gcoDesc");
    
    this.session.removeAttribute("brnCode");
    this.session.removeAttribute("pmasCode");
    
    this.session.removeAttribute("agnShtDesc");
    this.session.removeAttribute("agnName");
    this.session.removeAttribute("agnCode");
    
    this.session.removeAttribute("qcvtcvtCode");
    this.session.removeAttribute("taxCode");
    
    this.session.removeAttribute("pprov_Code");
    this.session.removeAttribute("dtyCode");
    this.session.removeAttribute("maxTypeNo");
    this.session.removeAttribute("qdlCode");
    this.session.removeAttribute("qmemCode");
    this.session.removeAttribute("fclCalcType");
    this.session.removeAttribute("provCode");
    this.session.removeAttribute("lcaCode");
    this.session.removeAttribute("dpdsCovered");
    this.session.removeAttribute("memberANB");
    this.session.removeAttribute("memGender");
    this.session.removeAttribute("ContrType");
    this.session.removeAttribute("savider");
    this.session.removeAttribute("pensionType");
    this.session.removeAttribute("quoCalcTypeM");
    this.session.removeAttribute("quoType");
    this.session.removeAttribute("paymentFrequency");
    this.session.removeAttribute("durType");
    this.session.removeAttribute("ttCode");
    this.session.removeAttribute("trtRate");
    this.session.removeAttribute("trtCode");
    this.session.removeAttribute("trtRateType");
    this.session.removeAttribute("ttRenewalEndos");
    this.session.removeAttribute("ttShtDesc");
    this.session.removeAttribute("qcprCode");
    this.session.setAttribute("CoinsurerTotal", Integer.valueOf(0));
    this.session.removeAttribute("TicketRemarks");
    this.session.setAttribute("SetAssignee", "N");
    this.session.setAttribute("ModuleTickets", "N");
    this.session.setAttribute("CreateUWClient", "N");
    this.session.removeAttribute("Endorsement");
    this.session.removeAttribute("policyCode");
    this.session.removeAttribute("endorsementCode");
    this.session.removeAttribute("transactionNumber");
    this.session.removeAttribute("pcvtCode");
    this.session.removeAttribute("PolCalcType");
    this.session.removeAttribute("policyNumber");
    this.session.removeAttribute("pmrid_code");
    this.session.removeAttribute("pcaCode");
    this.session.removeAttribute("endrPayMethd");
    this.session.removeAttribute("policyEffectiveDate");
    this.session.removeAttribute("frequencyOfPayment");
    this.session.removeAttribute("calculationType");
    this.session.removeAttribute("retirementAge");
    this.session.removeAttribute("policyDurationType");
    this.session.removeAttribute("durationType");
    this.session.removeAttribute("pensSchemeType");
    this.session.removeAttribute("checkOffAgentCode");
    this.session.removeAttribute("checkOffCommission");
    this.session.removeAttribute("membersToUpdate");
    this.session.removeAttribute("polpCode");
    this.session.removeAttribute("pprovCode");
    this.session.removeAttribute("pdlCode");
    this.session.removeAttribute("maxType");
    this.session.removeAttribute("rdCode");
    this.session.removeAttribute("rdShtDesc");
    this.session.removeAttribute("gpdCode");
    this.session.removeAttribute("documentSubmission");
    this.session.removeAttribute("gpdCode");
    this.session.removeAttribute("documentSubmission");
    this.session.removeAttribute("ptxCode");
    this.session.removeAttribute("savingsRider");
    this.session.removeAttribute("brnCode");
    this.session.removeAttribute("brnName");
    this.session.removeAttribute("pmasCode");
    this.session.removeAttribute("pmasShtDesc");
    this.session.removeAttribute("agnCode");
    this.session.removeAttribute("agnShtDesc");
    this.session.removeAttribute("agnName");
    this.session.setAttribute("UWStart", "No");
    this.session.setAttribute("Credit", "No");
    this.session.setAttribute("ClientExists", "Yes");
    this.session.removeAttribute("PolicyMemCode");
    this.session.removeAttribute("CausationCode");
    this.session.removeAttribute("CausationShtDesc");
    this.session.removeAttribute("CausationType");
    this.session.removeAttribute("ClaimNo");
    this.session.removeAttribute("ClaimTransNo");
    this.session.removeAttribute("CauseCode");
    this.session.setAttribute("EditClaim", Integer.valueOf(0));
    this.session.removeAttribute("ActivityCode");
    this.session.removeAttribute("CPVoucher");
    this.session.removeAttribute("voucherNumber");
    this.session.removeAttribute("quoteState");
    this.session.removeAttribute("quoteDateFrom");
    this.session.removeAttribute("quoteDateTo");
    this.session.removeAttribute("FCLTotalAmt");
    this.session.removeAttribute("TaskActivityName");
    this.session.removeAttribute("quaCode");
    this.session.removeAttribute("FacilitatorCode");
    this.session.removeAttribute("QuotCalcType");
    this.session.removeAttribute("IndMemNo");
    this.session.removeAttribute("RenDateFrom");
    this.session.removeAttribute("RenDateTo");
    this.session.setAttribute("DocSubmitted", "Y");
    this.session.removeAttribute("stateCode");
    this.session.removeAttribute("clientPRPCode");
    this.session.removeAttribute("PstCode");
    this.session.removeAttribute("LntCode");
    this.session.removeAttribute("LstCode");
    this.session.removeAttribute("ClaCode");
    this.session.removeAttribute("ActCode");
    this.session.removeAttribute("AtrCode");
    this.session.removeAttribute("FCLCode");
    this.session.setAttribute("SetupScrnID", Integer.valueOf(0));
    this.session.removeAttribute("txrCode");
    this.session.removeAttribute("sprCode");
    this.session.removeAttribute("facCode");
    this.session.removeAttribute("mtlCode");
    this.session.removeAttribute("pcdCode");
    this.session.removeAttribute("grptCode");
    this.session.removeAttribute("gpirCode");
    this.session.removeAttribute("gprCode");
    this.session.removeAttribute("pctCode");
    this.session.removeAttribute("dtyShtDesc");
    this.session.removeAttribute("cvtCode");
    this.session.removeAttribute("cvtShtDesc");
    this.session.removeAttribute("mtgCode");
    this.session.removeAttribute("trtgCode");
    this.session.removeAttribute("trsCode");
    this.session.removeAttribute("trtshtDesc");
    this.session.removeAttribute("trtgshtDesc");
    this.session.removeAttribute("manbCode");
    this.session.removeAttribute("mreqCode");
    this.session.removeAttribute("orrpCode");
    this.session.removeAttribute("orrtCode");
    this.session.removeAttribute("riosCode");
    this.session.removeAttribute("riotCode");
    this.session.setAttribute("AddEdit", "A");
    this.session.removeAttribute("ClientCode");
    this.session.removeAttribute("AGN_CODE");
    this.session.removeAttribute("ACT_CODE");
    this.session.removeAttribute("GrpLifeRider");
    this.session.removeAttribute("ReceiptTransNo");
    this.session.removeAttribute("GrctCode");
    this.session.removeAttribute("gfrtCode");
    this.session.setAttribute("recptsThruVal", "N");
    this.session.setAttribute("searchTab", "true");
    this.session.setAttribute("detailsTab", "false");
    this.session.setAttribute("withdrawalTab", "false");
    this.session.removeAttribute("pctl_code");
    this.session.removeAttribute("grp_single_rate");
    this.session.removeAttribute("provlCode");
    this.session.removeAttribute("btsCode");
    this.session.removeAttribute("pbgtCode");
    this.session.removeAttribute("chq_trans_type");
    this.session.removeAttribute("chq_date_from");
    this.session.removeAttribute("chq_date_to");
    this.session.removeAttribute("earningsType");
    this.session.removeAttribute("jointMem");
    this.session.removeAttribute("loanCalcType");
    this.session.removeAttribute("module");
    this.session.removeAttribute("riMedicals");
    this.session.removeAttribute("prmCode");
    this.session.removeAttribute("taxType");
    this.session.removeAttribute("sourcePage");
    this.session.removeAttribute("COP_CODE");
    this.session.removeAttribute("cmbCode");
    this.session.removeAttribute("selectAll");
    this.session.removeAttribute("selectAllDocs");
    this.session.removeAttribute("DateFrom");
    this.session.removeAttribute("DateTo");
    this.session.removeAttribute("periodFrom");
    this.session.removeAttribute("periodTo");
  }
  
  public String ReinitializeVar2()
  {
    this.session.setAttribute("searchTab", "true");
    this.session.setAttribute("detailsTab", "false");
    this.session.setAttribute("withdrawalTab", "false");
    this.session.setAttribute("recptsThruVal", "N");
    this.session.setAttribute("exclQuotes", "NONE");
    this.session.removeAttribute("QuotationNo");
    this.session.setAttribute("taxtypeAppl", "Y");
    
    this.session.removeAttribute("ProductCode");
    this.session.removeAttribute("productType");
    this.session.removeAttribute("CurrentStatus");
    this.session.removeAttribute("ProductLapsationDays");
    this.session.removeAttribute("LapseType");
    LOVCC.CoversSaved = 0;
    
    this.session.removeAttribute("TaxesCode");
    this.session.removeAttribute("ta_code");
    
    this.session.removeAttribute("TaxRateType");
    this.session.removeAttribute("TaxRenewalEndr");
    this.session.removeAttribute("TaxShtDesc");
    this.session.removeAttribute("TaxTRTCode");
    this.session.removeAttribute("qcvtCode");
    this.session.removeAttribute("QuoteCode");
    
    this.session.removeAttribute("MemberNumber");
    this.session.removeAttribute("CMLCode");
    this.session.removeAttribute("PaymentsFlag");
    this.session.removeAttribute("MedPolicy");
    this.session.removeAttribute("MedTransNo");
    this.session.removeAttribute("CMICode");
    this.session.removeAttribute("MedicalScrnRender");
    this.session.removeAttribute("QuotCalcType");
    
    this.session.removeAttribute("sysModule");
    this.session.removeAttribute("msgType");
    this.session.removeAttribute("AgentCode");
    LOVCC.TransactionNumber = null;
    
    this.session.removeAttribute("UWYear");
    this.session.removeAttribute("ValuationPeriod");
    LOVCC.DeductionCode = null;
    LOVCC.PDED_CODE = null;
    LOVCC.Allocated = null;
    this.session.removeAttribute("townCode");
    this.session.removeAttribute("countryCode");
    this.session.removeAttribute("sectorCode");
    this.session.removeAttribute("branchCode");
    this.session.removeAttribute("postalZIPCode");
    this.session.removeAttribute("domicileCountry");
    this.session.removeAttribute("sectorName");
    this.session.removeAttribute("occupationCode");
    this.session.removeAttribute("occupationCode");
    this.session.removeAttribute("occupationDesc");
    this.session.removeAttribute("branchName");
    this.session.removeAttribute("townName");
    this.session.removeAttribute("countryShtDesc");
    LOVCC.clientName = null;
    LOVCC.clientexists = false;
    
    this.session.removeAttribute("occupationlifeClass");
    LOVCC.enquiryMode = false;
    
    this.session.setAttribute("ScreenPosition", Integer.valueOf(0));
    this.session.removeAttribute("ReceiptTransNo");
    this.session.removeAttribute("TicketRemarks");
    this.session.setAttribute("SetAssignee", "N");
    this.session.setAttribute("ModuleTickets", "N");
    this.session.setAttribute("CreateUWClient", "N");
    
    this.session.removeAttribute("Endorsement");
    
    this.session.removeAttribute("prpCode");
    this.session.removeAttribute("prpDesc");
    this.session.removeAttribute("gcoCode");
    this.session.removeAttribute("gcoDesc");
    
    this.session.removeAttribute("brnCode");
    this.session.removeAttribute("pmasCode");
    this.session.removeAttribute("agnShtDesc");
    this.session.removeAttribute("agnName");
    this.session.removeAttribute("agnCode");
    
    this.session.removeAttribute("qcvtcvtCode");
    this.session.removeAttribute("taxCode");
    this.session.removeAttribute("pprov_Code");
    this.session.removeAttribute("dtyCode");
    this.session.removeAttribute("dtyShtDesc");
    this.session.removeAttribute("maxTypeNo");
    this.session.removeAttribute("qdlCode");
    this.session.removeAttribute("qmemCode");
    this.session.removeAttribute("fclCalcType");
    this.session.removeAttribute("provCode");
    this.session.removeAttribute("lcaCode");
    this.session.removeAttribute("dpdsCovered");
    this.session.removeAttribute("memberANB");
    this.session.removeAttribute("memGender");
    this.session.removeAttribute("ContrType");
    this.session.removeAttribute("savider");
    this.session.removeAttribute("pensionType");
    this.session.removeAttribute("quoCalcTypeM");
    this.session.removeAttribute("quoType");
    this.session.removeAttribute("paymentFrequency");
    this.session.removeAttribute("durType");
    this.session.removeAttribute("ttCode");
    this.session.removeAttribute("trtRate");
    this.session.removeAttribute("trtCode");
    this.session.removeAttribute("trtRateType");
    this.session.removeAttribute("ttRenewalEndos");
    this.session.removeAttribute("ttShtDesc");
    this.session.removeAttribute("qcprCode");
    this.session.setAttribute("CoinsurerTotal", Integer.valueOf(0));
    this.session.removeAttribute("pdedCode");
    
    this.session.removeAttribute("policyCode");
    this.session.removeAttribute("endorsementCode");
    this.session.removeAttribute("transactionNumber");
    this.session.removeAttribute("pcvtCode");
    this.session.removeAttribute("PolCalcType");
    this.session.removeAttribute("policyNumber");
    this.session.removeAttribute("pmrid_code");
    this.session.removeAttribute("pcaCode");
    this.session.removeAttribute("endrPayMethd");
    this.session.removeAttribute("policyEffectiveDate");
    this.session.removeAttribute("frequencyOfPayment");
    this.session.removeAttribute("calculationType");
    this.session.removeAttribute("retirementAge");
    this.session.removeAttribute("policyDurationType");
    this.session.removeAttribute("durationType");
    this.session.removeAttribute("pensSchemeType");
    this.session.removeAttribute("checkOffAgentCode");
    this.session.removeAttribute("checkOffCommission");
    this.session.removeAttribute("membersToUpdate");
    this.session.removeAttribute("polpCode");
    this.session.removeAttribute("pprovCode");
    this.session.removeAttribute("pdlCode");
    this.session.removeAttribute("maxType");
    this.session.removeAttribute("rdCode");
    this.session.removeAttribute("rdShtDesc");
    this.session.removeAttribute("gpdCode");
    this.session.removeAttribute("documentSubmission");
    this.session.removeAttribute("gpdCode");
    this.session.removeAttribute("documentSubmission");
    this.session.removeAttribute("ptxCode");
    this.session.removeAttribute("savingsRider");
    
    this.session.removeAttribute("brnCode");
    this.session.removeAttribute("brnName");
    this.session.removeAttribute("pmasCode");
    this.session.removeAttribute("pmasShtDesc");
    this.session.removeAttribute("agnCode");
    this.session.removeAttribute("agnShtDesc");
    this.session.removeAttribute("agnName");
    this.session.setAttribute("UWStart", "No");
    this.session.setAttribute("Credit", "No");
    this.session.setAttribute("ClientExists", "Yes");
    this.session.removeAttribute("PolicyMemCode");
    this.session.removeAttribute("CausationCode");
    this.session.removeAttribute("CausationShtDesc");
    this.session.removeAttribute("CausationType");
    this.session.removeAttribute("ClaimNo");
    this.session.removeAttribute("ClaimTransNo");
    this.session.removeAttribute("CauseCode");
    this.session.setAttribute("EditClaim", Integer.valueOf(0));
    this.session.removeAttribute("ActivityCode");
    this.session.removeAttribute("CPVoucher");
    this.session.removeAttribute("voucherNumber");
    
    this.session.removeAttribute("quoteState");
    this.session.removeAttribute("quoteDateFrom");
    this.session.removeAttribute("quoteDateTo");
    this.session.removeAttribute("FCLTotalAmt");
    this.session.removeAttribute("TaskActivityName");
    this.session.removeAttribute("EndorsementStatus");
    this.session.removeAttribute("quaCode");
    this.session.removeAttribute("FacilitatorCode");
    this.session.removeAttribute("IndMemNo");
    this.session.removeAttribute("RenDateFrom");
    this.session.removeAttribute("RenDateTo");
    this.session.setAttribute("instPrem", Integer.valueOf(0));
    this.session.setAttribute("DocSubmitted", "Y");
    this.session.setAttribute("ClientAccept", "Accept");
    this.session.removeAttribute("stateCode");
    this.session.removeAttribute("clientPRPCode");
    this.session.removeAttribute("PstCode");
    this.session.removeAttribute("LntCode");
    this.session.removeAttribute("LstCode");
    this.session.removeAttribute("ClaCode");
    this.session.removeAttribute("ActCode");
    this.session.removeAttribute("AtrCode");
    this.session.setAttribute("SetupScrnID", Integer.valueOf(0));
    this.session.removeAttribute("FCLCode");
    this.session.removeAttribute("txrCode");
    this.session.removeAttribute("sprCode");
    this.session.removeAttribute("facCode");
    this.session.removeAttribute("mtlCode");
    this.session.removeAttribute("pcdCode");
    this.session.removeAttribute("grptCode");
    this.session.removeAttribute("gpirCode");
    this.session.removeAttribute("gprCode");
    this.session.removeAttribute("pctCode");
    this.session.removeAttribute("mtgCode");
    this.session.removeAttribute("trtgCode");
    this.session.removeAttribute("trsCode");
    this.session.removeAttribute("trtshtDesc");
    this.session.removeAttribute("trtgshtDesc");
    this.session.removeAttribute("manbCode");
    this.session.removeAttribute("mreqCode");
    this.session.removeAttribute("lcCode");
    this.session.removeAttribute("gfmCode");
    this.session.removeAttribute("orrpCode");
    this.session.removeAttribute("orrtCode");
    this.session.removeAttribute("riosCode");
    this.session.removeAttribute("riotCode");
    this.session.setAttribute("AddEdit", "A");
    this.session.removeAttribute("ClientCode");
    this.session.removeAttribute("AGN_CODE");
    this.session.removeAttribute("ACT_CODE");
    this.session.removeAttribute("classCatCode");
    this.session.removeAttribute("classTermLimCode");
    this.session.removeAttribute("CategoryShtDesc");
    this.session.removeAttribute("QuoteCategoryShtDesc");
    
    this.session.setAttribute("facPlacements", "N");
    this.session.removeAttribute("studentBenCode");
    this.session.removeAttribute("ClassSchLevel");
    this.session.removeAttribute("schLevel");
    this.session.removeAttribute("VoucherDecision");
    this.session.setAttribute("coversAvail", "N");
    
    this.session.removeAttribute("action");
    
    this.session.removeAttribute("GrctCode");
    this.session.removeAttribute("PNDP_CODE");
    this.session.removeAttribute("GrpLifeRider");
    this.session.removeAttribute("reusePolCode");
    this.session.removeAttribute("endrValue");
    this.session.removeAttribute("delExistMembers");
    this.session.removeAttribute("callScreen");
    this.session.removeAttribute("newWETDate");
    this.session.setAttribute("editComponents", "N");
    this.session.removeAttribute("pendingClaim");
    this.session.removeAttribute("CTL_QUO_LCA_CODE");
    this.session.removeAttribute("CTL_CODE");
    this.session.removeAttribute("gblCode");
    this.session.setAttribute("RIProcessing", "N");
    this.session.removeAttribute("rateAmt");
    this.session.removeAttribute("reinsPmasCode");
    this.session.removeAttribute("pensTransType");
    this.session.removeAttribute("withdrawalReceipt");
    this.session.removeAttribute("CoinsPolicy");
    this.session.removeAttribute("rptProductCode");
    this.session.removeAttribute("CoinsLeadFollow");
    this.session.setAttribute("benModule", "P");
    this.session.removeAttribute("CRAMTRANCODE");
    this.session.removeAttribute("craRefNo");
    this.session.removeAttribute("craAmount");
    this.session.removeAttribute("pensionPayee");
    this.session.removeAttribute("scheduleNo");
    this.session.removeAttribute("qabCode");
    this.session.removeAttribute("pabCode");
    this.session.removeAttribute("gagnCode");
    this.session.removeAttribute("govtAuthCode");
    this.session.setAttribute("receiptTemplateSeq", Integer.valueOf(0));
    this.session.removeAttribute("agnNameSearch");
    this.session.removeAttribute("pcfrCode");
    this.session.removeAttribute("prevEndrCode");
    this.session.removeAttribute("prevTransNo");
    this.session.removeAttribute("coAgnCode");
    this.session.removeAttribute("lgcaCode");
    this.session.removeAttribute("action2");
    this.session.setAttribute("pastPeriod", "N");
    this.session.setAttribute("loadedPolEndorsement", "N");
    this.session.setAttribute("booleanSelect", "F");
    this.session.removeAttribute("pgvsCode");
    this.session.removeAttribute("pcyCode");
    this.session.setAttribute("prodSpecific", "N");
    this.session.setAttribute("RenewalArea", "N");
    this.session.setAttribute("coinsLevel", "P");
    this.session.setAttribute("allocationType", "ND");
    this.session.removeAttribute("mktCode");
    this.session.removeAttribute("mktShtDesc");
    this.session.removeAttribute("gfrtCode");
    this.session.removeAttribute("schCode");
    this.session.removeAttribute("endrType");
    this.session.removeAttribute("monthValue");
    this.session.setAttribute("depCovered", "S");
    this.session.setAttribute("importstate", "A");
    this.session.setAttribute("TotalMembers", new BigDecimal("0"));
    this.session.setAttribute("ValidMembers", new BigDecimal("0"));
    this.session.setAttribute("InValidMembers", new BigDecimal("0"));
    this.session.setAttribute("allCovers", "N");
    this.session.removeAttribute("cloneProdCode");
    this.session.removeAttribute("jointAgentCode");
    this.session.removeAttribute("categoryMaskCode");
    this.session.removeAttribute("coverMaskCode");
    this.session.removeAttribute("JointagnCode");
    this.session.removeAttribute("lpagPolicyCode");
    this.session.removeAttribute("lpagCode");
    this.session.removeAttribute("catlpagCode");
    this.session.removeAttribute("lpagDesc");
    this.session.setAttribute("disableDurationSel", "N");
    this.session.setAttribute("umbrellaCover", "N");
    this.session.setAttribute("umbrellaDurationType", "A");
    this.session.removeAttribute("subdivisionCode");
    this.session.removeAttribute("QuotedivisionCode");
    this.session.removeAttribute("rptLCACode");
    this.session.removeAttribute("PolicydivisionCode");
    this.session.setAttribute("TicketModule", "P");
    this.session.setAttribute("calcType", "D");
    this.session.removeAttribute("grp_single_rate");
    this.session.removeAttribute("emdCode");
    this.session.removeAttribute("emailUsr");
    this.session.removeAttribute("alertMsg");
    this.session.removeAttribute("earningsType");
    this.session.removeAttribute("jointMem");
    this.session.removeAttribute("loanCalcType");
    this.session.removeAttribute("module");
    this.session.removeAttribute("riMedicals");
    this.session.removeAttribute("MemberNumber1");
    this.session.removeAttribute("prmCode");
    this.session.removeAttribute("pbgtCode");
    this.session.removeAttribute("taxType");
    this.session.removeAttribute("sourcePage");
    this.session.removeAttribute("COP_CODE");
    this.session.removeAttribute("cmbCode");
    this.session.removeAttribute("selectAll");
    this.session.removeAttribute("selectAllDocs");
    this.session.removeAttribute("DateFrom");
    this.session.removeAttribute("DateTo");
    this.session.removeAttribute("periodFrom");
    this.session.removeAttribute("periodTo");
    
    return null;
  }
}
