BEGIN
Insert into TQC_SYS_RPT_TEMPLATES
   (RPT_TMPL_CODE, RPT_TMPL_RPT_CODE, RPT_TMPL_FILE, RPT_TMPL_NAME, RPT_TMPL_DESCRIPTION, 
    RPT_TMPL_STYLE_FILE, RPT_TMPL_ORG_CODE, RPT_TMPL_ACTIVE)
 Values
   (3509, 780, 'PENDING_CLAIMS_APOLLO_TEMP.rtf', 'PENDING_CLAIMS_TMP', 'Pending Claims Report', 
    'PENDING_CLAIMS_APOLLO_TEMP.xsl', NULL, 'A');
COMMIT;
END;
/