BEGIN
Insert into TQC_SYSTEM_REPORTS
   (RPT_CODE, RPT_SYS_CODE, RPT_NAME, RPT_DESCRIPTION, RPT_DATA_FILE, 
    RPT_APPLCTN_LEVEL, RPT_ACTIVE)
 Values
   (2171, 27, 'RETURN_ON_CONTRIBUTION', 'Return on Contribution', 'contri_return.xml', 
    NULL, 'A');
Insert into TQC_SYS_RPT_TEMPLATES
   (RPT_TMPL_CODE, RPT_TMPL_RPT_CODE, RPT_TMPL_FILE, RPT_TMPL_NAME, RPT_TMPL_DESCRIPTION, 
    RPT_TMPL_STYLE_FILE, RPT_TMPL_ORG_CODE, RPT_TMPL_ACTIVE)
 Values
   (3510, 2171, 'contri_return_temp.rtf', 'RETURN_ON_CONTRIBUTION_RPT', 'Return on contribution Template', 
    'contri_return_temp.xsl', NULL, 'A');
Insert into TQC_SYS_RPT_PARAMETERS
   (RPTP_CODE, RPTP_RPT_CODE, RPTP_PARAM_NAME, RPTP_PARAM_DESC, RPTP_PARAM_PROMPT, 
    RPTP_PARAM_TYPE, RPTP_PARENT_CODE, RPTP_QUERY, RPTP_PARAM_CLAUSE, RPTP_USER_REQUIRED, 
    RPTP_CHILD_CODE, RPTP_PARAM_ACTIVE)
 Values
   (25089, 2171, 'V_DATE_FROM', 'DATE FROM', 'Date From', 
    'DATE', NULL, NULL, NULL, NULL, 
    NULL, 'A');
Insert into TQC_SYS_RPT_PARAMETERS
   (RPTP_CODE, RPTP_RPT_CODE, RPTP_PARAM_NAME, RPTP_PARAM_DESC, RPTP_PARAM_PROMPT, 
    RPTP_PARAM_TYPE, RPTP_PARENT_CODE, RPTP_QUERY, RPTP_PARAM_CLAUSE, RPTP_USER_REQUIRED, 
    RPTP_CHILD_CODE, RPTP_PARAM_ACTIVE)
 Values
   (25090, 2171, 'V_DATE_TO', 'DATE TO', 'Date To', 
    'DATE', NULL, NULL, NULL, NULL, 
    NULL, 'A');
COMMIT;
END;
/
