Insert into TQC_SYS_PROCESS_SUB_AREAS
   (SPRSA_CODE, SPRSA_SPRCA_CODE, SPRSA_SPRC_CODE, SPRSA_SUB_AREA, SPRSA_TYPE, 
    SPRSA_SHT_DESC, SPRSA_DEFAULT_USR_CODE)
 Values
   (1836, 322, 261, 'AUTHORIZE_CLAIM_VOUCHERS', 'A', 
    'CLMA', NULL);