DECLARE
CURSOR POL
IS
     SELECT 'DA/2005/37' POL_NO FROM DUAL
     UNION
     SELECT 'DA/2005/38' POL_NO FROM DUAL
     UNION
     SELECT 'DA/2005/39' POL_NO FROM DUAL;
     
CURSOR C(V_POL_NO VARCHAR2) IS
SELECT * FROM LMS_PENS_TEMP_BAL
WHERE POL_NO=V_POL_NO
AND STATUS='N';

V_COUNT NUMBER;

V_POLM_CODE NUMBER;
V_POL_CODE NUMBER;
V_TOTAL_EMPYE_BAL NUMBER := 0;
V_TOTAL_EMPYR_BAL NUMBER :=0 ;

    BEGIN
    
    DELETE FROM LMS_PENSION_BALANCES_PERIODS
    WHERE pnbalp_pol_code
    IN(SELECT POL_CODE FROM LMS_POLICIES
    WHERE POL_POLICY_NO IN('DA/2005/37','DA/2005/38','DA/2005/39'))
    AND PNBALP_YEAR=2012;
    
    UPDATE LMS_PENSION_BALANCES
    SET  PNBAL_EMPYR_BAL_BF=0,
    PNBAL_EMPYE_BAL_BF=0,
    PNBAL_EMPYR_BAL_INCOME=0,
    PNBAL_EMPYE_BAL_INCOME=0,
    PNBAL_EMPYR_BAL_CF=0,
    PNBAL_EMPYE_BAL_CF=0,
    PNBAL_TOTAL_FUND_BAL=0,
    PNBAL_TOT_BAL_CF=0,
    PNBAL_TOT_AMT=0
    WHERE PNBAL_POL_CODE IN(SELECT POL_CODE FROM LMS_POLICIES
    WHERE POL_POLICY_NO IN('DA/2005/37','DA/2005/38','DA/2005/39'))
    AND PNBAL_YEAR=2012;
    
FOR POL_CUR IN POL
LOOP
    FOR C1 IN C (POL_CUR.POL_NO)
    LOOP

        BEGIN
        SELECT POLM_CODE,POLM_POL_CODE
        INTO V_POLM_CODE,V_POL_CODE
        FROM LMS_POLICY_MEMBERS,LMS_MEMBERS
        WHERE POLM_MEM_CODE=MEM_CODE
        AND POLM_POL_POLICY_NO=C1.POL_NO
        AND MEM_NO=C1.MEM_NO;
        EXCEPTION
        WHEN NO_DATA_FOUND THEN
        V_POLM_CODE :=0;
        WHEN OTHERS THEN
        NULL;
        END;

        IF V_POLM_CODE !=0
        THEN
            BEGIN
            
               
                UPDATE LMS_PENSION_MEM_DEPOSITS
                SET PNMDP_EMPYR_AMT=0,
                    PNMDP_EMPYE_AMT=0,
                    PNMDP_EMPYE_VOL_AMT=0,
                    PNMDP_AMOUNT=0,
                    PNMDP_TOT_AMT=0,
                    PNMDP_EMPYR_REG_AMT=0,
                    PNMDP_EMPYE_REG_AMT=0
                 WHERE PNMDP_POL_CODE=V_POL_CODE
                AND PNMDP_YEAR=2012;
                
                UPDATE LMS_PENSION_MEM_BALANCES
                SET PNMBAL_EMPYR_BAL_CF=0,
                PNMBAL_EMPYE_BAL_CF=0,
                PNMBAL_EMPYR_BAL_BF=0,
                PNMBAL_EMPYE_BAL_BF=0                
                WHERE PNMBAL_POL_CODE=V_POL_CODE
                AND PNMBAL_YEAR=2012;

                BEGIN
                UPDATE LMS_PENSION_MEM_BALANCES
                SET PNMBAL_EMPYR_BAL_CF=C1.EMPYR_BAL,
                PNMBAL_EMPYE_BAL_CF=C1.EMPYE_BAL,
                PNMBAL_EMPYR_BAL_BF=0,
                PNMBAL_EMPYE_BAL_BF=0
                WHERE PNMBAL_POLM_CODE=V_POLM_CODE
                AND PNMBAL_POL_CODE=V_POL_CODE
                AND PNMBAL_YEAR=2012;

                UPDATE LMS_PENSION_MEM_BALANCES
                SET PNMBAL_EMPYR_BAL_BF=C1.EMPYR_BAL,
                PNMBAL_EMPYE_BAL_BF=C1.EMPYE_BAL
                WHERE PNMBAL_POLM_CODE=V_POLM_CODE
                AND PNMBAL_POL_CODE=V_POL_CODE
                AND PNMBAL_YEAR=2013;                
                
                END;
                V_TOTAL_EMPYR_BAL :=V_TOTAL_EMPYR_BAL+C1.EMPYR_BAL;
                V_TOTAL_EMPYE_BAL :=V_TOTAL_EMPYE_BAL+C1.EMPYE_BAL;

                UPDATE LMS_PENS_TEMP_BAL
                SET STATUS='A'
                WHERE MEM_NO=C1.MEM_NO;
            END;

        

        END IF;
       
    END LOOP;
    
        
        UPDATE LMS_PENSION_BALANCES
                SET PNBAL_EMPYR_BAL_CF=PNBAL_EMPYR_BAL_CF+V_TOTAL_EMPYR_BAL,
                PNBAL_EMPYE_BAL_CF=PNBAL_EMPYE_BAL_CF+V_TOTAL_EMPYE_BAL,
                PNBAL_TOT_BAL_CF=PNBAL_TOT_BAL_CF+(V_TOTAL_EMPYR_BAL+V_TOTAL_EMPYE_BAL),
                PNBAL_TOTAL_FUND_BAL=PNBAL_TOTAL_FUND_BAL+(V_TOTAL_EMPYR_BAL+V_TOTAL_EMPYE_BAL),
                PNBAL_SCHEME_FUND=PNBAL_SCHEME_FUND+(V_TOTAL_EMPYR_BAL+V_TOTAL_EMPYE_BAL),
                PNBAL_EMPYR_BAL_BF=0,
                PNBAL_EMPYE_BAL_BF=0,
                PNBAL_EMPYE_AMT=0,
                PNBAL_EMPYR_AMT=0
                WHERE PNBAL_POL_CODE=V_POL_CODE
                AND PNBAL_YEAR=2012;

                 UPDATE LMS_PENSION_DEPOSITS
                    SET PNDP_EMPYR_AMT=0,
                        PNDP_EMPYE_AMT=0,
                        PNDP_EMPYE_VOL_AMT=0,
                        PNDP_AMOUNT=0,
                        PNDP_EMPYR_INT=0,
                        PNDP_EMPYE_INT=0
                    WHERE PNDP_POL_CODE=V_POL_CODE
                    AND  PNDP_YEAR=2012;

                UPDATE LMS_PENSION_BALANCES
                SET PNBAL_EMPYR_BAL_BF=PNBAL_EMPYR_BAL_BF+V_TOTAL_EMPYR_BAL,
                PNBAL_EMPYE_BAL_BF=PNBAL_EMPYE_BAL_BF+V_TOTAL_EMPYE_BAL
                WHERE PNBAL_POL_CODE=V_POL_CODE
                AND PNBAL_YEAR=2013;
     
        BEGIN
                
                
           INSERT INTO LMS_PENSION_BALANCES_PERIODS
           (PNBALP_CODE,PNBALP_EMPYE_BAL_CF,PNBALP_EMPYR_BAL_CF,PNBALP_VALUA_DATE,
           PNBALP_WEF,PNBALP_WET,PNBALP_YEAR,PNBALP_STATUS,PNBALP_POL_CODE,PNBALP_SCHEME_FUND)   
           VALUES(LMS_PNBALP_CODE_SEQ.NEXTVAL,V_TOTAL_EMPYE_BAL,V_TOTAL_EMPYR_BAL,TO_DATE('31/12/2012','DD/MM/RRRR'),
           TO_DATE('01/01/2012','DD/MM/RRRR'),TO_DATE('31/12/2012','DD/MM/RRRR'),2012,'A',V_POL_CODE,V_TOTAL_EMPYE_BAL+V_TOTAL_EMPYR_BAL); 

          END;
            
 END LOOP;     
            

COMMIT;

END;
/

