BEGIN
Insert into TQC_SYSTEM_REPORTS
   (RPT_CODE, RPT_SYS_CODE, RPT_NAME, RPT_DESCRIPTION, RPT_DATA_FILE, 
    RPT_APPLCTN_LEVEL, RPT_ACTIVE)
 Values
   (2251, 27, 'GRP_VAL_RPT', 'Group Valuation Report', 'grp_val.xml', 
    NULL, 'A');
Insert into TQC_SYS_RPT_PARAMETERS
   (RPTP_CODE, RPTP_RPT_CODE, RPTP_PARAM_NAME, RPTP_PARAM_DESC, RPTP_PARAM_PROMPT, 
    RPTP_PARAM_TYPE, RPTP_PARENT_CODE, RPTP_QUERY, RPTP_PARAM_CLAUSE, RPTP_USER_REQUIRED, 
    RPTP_CHILD_CODE, RPTP_PARAM_ACTIVE)
 Values
   (TQC_RPTP_CODE_SEQ.NEXTVAL, 2251, 'GRP_TRANS_TYPE', 'Group Life Transactions', 'Group Life Transactions', 
    'LOV', NULL, 'SELECT DISTINCT ENDR_TYPE,BTR_TRANS_TYPE FROM LMS_POLICY_ENDORSEMENTS,LMS_POLICIES,LMS_BUSINESS_TRANSACTIONS 
WHERE ENDR_TYPE=BTR_TRANS_CODE
AND ENDR_POL_CODE=POL_CODE
AND POL_PROD_SHT_DESC=''GLA''
AND ENDR_TYPE IN(''NB'',''RN'',''AP'')
ORDER BY ENDR_TYPE ASC', NULL, NULL, 
    NULL, 'A');
Insert into TQC_SYS_RPT_PARAMETERS
   (RPTP_CODE, RPTP_RPT_CODE, RPTP_PARAM_NAME, RPTP_PARAM_DESC, RPTP_PARAM_PROMPT, 
    RPTP_PARAM_TYPE, RPTP_PARENT_CODE, RPTP_QUERY, RPTP_PARAM_CLAUSE, RPTP_USER_REQUIRED, 
    RPTP_CHILD_CODE, RPTP_PARAM_ACTIVE)
 Values
   (TQC_RPTP_CODE_SEQ.NEXTVAL, 2251, 'V_DATE_FROM', 'START DATE', 'Start Date', 
    'DATE', NULL, NULL, NULL, NULL, 
    NULL, 'A');
Insert into TQC_SYS_RPT_PARAMETERS
   (RPTP_CODE, RPTP_RPT_CODE, RPTP_PARAM_NAME, RPTP_PARAM_DESC, RPTP_PARAM_PROMPT, 
    RPTP_PARAM_TYPE, RPTP_PARENT_CODE, RPTP_QUERY, RPTP_PARAM_CLAUSE, RPTP_USER_REQUIRED, 
    RPTP_CHILD_CODE, RPTP_PARAM_ACTIVE)
 Values
   (TQC_RPTP_CODE_SEQ.NEXTVAL , 2251, 'V_DATE_TO', 'END DATE', 'End Date', 
    'DATE', NULL, NULL, NULL, NULL, 
    NULL, 'A');
COMMIT;
END;
/
