ALTER TABLE TQ_LMS.LMS_QUOTATION_COVER_TYPES
ADD (QCVT_TOT_MEMBER_EARNINGS NUMBER(22,5));

COMMENT ON COLUMN 
TQ_LMS.LMS_QUOTATION_COVER_TYPES.QCVT_TOT_MEMBER_EARNINGS IS 
'STORES THE TOTAL EARNINGS FOR ALL THE MEMBERS IN THE QUOTE';

ALTER TABLE TQ_LMS.LMS_QUOTATION_COVER_TYPES
ADD (QCVT_TOT_ORIG_LOAN_AMT NUMBER(22,5));

COMMENT ON COLUMN 
TQ_LMS.LMS_QUOTATION_COVER_TYPES.QCVT_TOT_ORIG_LOAN_AMT IS 
'STORES THE TOTAL LOAN AMOUNT FOR ALL THE MEMBERS IN THE QUOTE';

ALTER TABLE TQ_LMS.LMS_QUOTATION_COVER_TYPES
ADD (QCVT_AV_CVR_PER_MEMBER NUMBER(22,5));

COMMENT ON COLUMN 
TQ_LMS.LMS_QUOTATION_COVER_TYPES.QCVT_AV_CVR_PER_MEMBER IS 
'STORES THE AVERAGE COVER PER MEMBER IN THE QUOTE';

