ALTER TABLE TQ_LMS.LMS_QUOTATION_CATEGORIES
ADD (LCA_PREV_LCA_CODE NUMBER(15) DEFAULT 15);

COMMENT ON COLUMN 
TQ_LMS.LMS_QUOTATION_CATEGORIES.LCA_PREV_LCA_CODE IS 
'COLUMN TO STORE THE PREVIOUS CATEGORY INCASE OF REVISION';
