BEGIN
Insert into TQC_SYS_RPT_TEMPLATES
   (RPT_TMPL_CODE, RPT_TMPL_RPT_CODE, RPT_TMPL_FILE, RPT_TMPL_NAME, RPT_TMPL_DESCRIPTION, 
    RPT_TMPL_STYLE_FILE, RPT_TMPL_ORG_CODE, RPT_TMPL_ACTIVE)
 Values
   (3312, 809, 'INDIV_VAL_RPTAIICO_TEMP.rtf', 'INDIV_VAL_RPT_TMP', 'Individual Valuation Report Aiico', 
    'INDIV_VAL_RPTAIICO_TEMP.xsl', NULL, 'A');
COMMIT;
END;
/