begin
Insert into TQC_SYSTEM_REPORTS
   (RPT_CODE, RPT_SYS_CODE, RPT_NAME, RPT_DESCRIPTION, RPT_DATA_FILE, 
    RPT_APPLCTN_LEVEL, RPT_ACTIVE)
 Values
   (1941, 27, 'PREM_SUMMARY_RPT', 'Premium Summary Report', 'premsum.xml', 
    NULL, 'A');
Insert into TQC_SYS_RPT_TEMPLATES
   (RPT_TMPL_CODE, RPT_TMPL_RPT_CODE, RPT_TMPL_FILE, RPT_TMPL_NAME, RPT_TMPL_DESCRIPTION, 
    RPT_TMPL_STYLE_FILE, RPT_TMPL_ORG_CODE, RPT_TMPL_ACTIVE)
 Values
   (3258, 1941, 'premsum_temp.rtf', 'PREM_SUMMARY_RPT', 'Premium Summary Report Template', 
    'premsum_temp.rtf.xsl', NULL, 'A');
COMMIT;
end;
/


BEGIN
Insert into TQC_SYS_RPT_PARAMETERS
   (RPTP_CODE, RPTP_RPT_CODE, RPTP_PARAM_NAME, RPTP_PARAM_DESC, RPTP_PARAM_PROMPT, 
    RPTP_PARAM_TYPE, RPTP_PARENT_CODE, RPTP_QUERY, RPTP_PARAM_CLAUSE, RPTP_USER_REQUIRED, 
    RPTP_CHILD_CODE, RPTP_PARAM_ACTIVE)
 Values
   (24575, 1941, 'V_POL_CODE', 'POLICY CODE(POL_CODE)', 'Policy', 
    'LOV', NULL, 'SELECT POL_CODE,POL_POLICY_NO,PRP_SURNAME||'' ''||PRP_OTHER_NAMES 
FROM LMS_PROPOSERS,LMS_POLICIES
WHERE POL_CLIENT_PRP_CODE=PRP_CODE
and POL_STATUS NOT IN (''C'',''PU'',''M'',''P'',''J'',''L'')
and pol_cla_code = (select cla_code from lms_classes where cla_type = ''G'') 
ORDER BY POL_CODE DESC', NULL, NULL, 
    NULL, 'A');
COMMIT;
END;
/