DECLARE
    CURSOR AGN IS
    SELECT DISTINCT POL_COIN_AGN_CODE FROM LMS_POLICY_COINSURERS
    WHERE POL_COIN_AGN_CODE NOT IN (SELECT AGN_CODE FROM lms_agencies);
  
 BEGIN
 FOR AGN_REC IN AGN LOOP
  BEGIN
    LMS_SETUPS_PKG.createNewAgent(AGN_REC.POL_COIN_AGN_CODE);
    COMMIT;
  EXCEPTION
    WHEN OTHERS THEN
    RAISE_APPLICATION_ERROR(-20001, 'Error Inserting Agent.');
  END; 
 END LOOP;
 END;