BEGIN
Insert into TQC_SYSTEM_REPORTS
   (RPT_CODE, RPT_SYS_CODE, RPT_NAME, RPT_DESCRIPTION, RPT_DATA_FILE, 
    RPT_APPLCTN_LEVEL, RPT_ACTIVE)
 Values
   (1861, 27, 'BRKS_BUS_RETURN', 'Brokers Business Return', 'BrksBusRet.xml', 
    NULL, 'A');
Insert into TQC_SYS_RPT_TEMPLATES
   (RPT_TMPL_CODE, RPT_TMPL_RPT_CODE, RPT_TMPL_FILE, RPT_TMPL_NAME, RPT_TMPL_DESCRIPTION, 
    RPT_TMPL_STYLE_FILE, RPT_TMPL_ORG_CODE, RPT_TMPL_ACTIVE)
 Values
   (3184, 1861, 'BrksBusRet_temp.rtf', 'BRKS_BUS_RETURN_RPT', 'Brokers Business Return', 
    'BrksBusRet_temp.xsl', NULL, 'A');
COMMIT;

END;
/

--registers report parameters--

begin
Insert into TQC_SYS_RPT_PARAMETERS
   (RPTP_CODE, RPTP_RPT_CODE, RPTP_PARAM_NAME, RPTP_PARAM_DESC, RPTP_PARAM_PROMPT, 
    RPTP_PARAM_TYPE, RPTP_PARENT_CODE, RPTP_QUERY, RPTP_PARAM_CLAUSE, RPTP_USER_REQUIRED, 
    RPTP_CHILD_CODE)
 Values
   (24453, 1861, 'START_DATE', 'START_DATE', 'Start Date', 
    'DATE', NULL, NULL, NULL, NULL, 
    NULL);
Insert into TQC_SYS_RPT_PARAMETERS
   (RPTP_CODE, RPTP_RPT_CODE, RPTP_PARAM_NAME, RPTP_PARAM_DESC, RPTP_PARAM_PROMPT, 
    RPTP_PARAM_TYPE, RPTP_PARENT_CODE, RPTP_QUERY, RPTP_PARAM_CLAUSE, RPTP_USER_REQUIRED, 
    RPTP_CHILD_CODE)
 Values
   (24454,1861, 'END_DATE', 'END_DATE', 'End Date', 
    'DATE', NULL, NULL, NULL, NULL, 
    NULL);
COMMIT;
end;
/