BEGIN
Insert into TQC_SYSTEM_REPORTS
   (RPT_CODE, RPT_SYS_CODE, RPT_NAME, RPT_DESCRIPTION, RPT_DATA_FILE, 
    RPT_APPLCTN_LEVEL, RPT_ACTIVE)
 Values
   (1862, 27, 'BRKS_STAT_ACCOUNT', 'Broker Statement Account', 'BrksStatement.xml', 
    NULL, 'A');
Insert into TQC_SYS_RPT_TEMPLATES
   (RPT_TMPL_CODE, RPT_TMPL_RPT_CODE, RPT_TMPL_FILE, RPT_TMPL_NAME, RPT_TMPL_DESCRIPTION, 
    RPT_TMPL_STYLE_FILE, RPT_TMPL_ORG_CODE, RPT_TMPL_ACTIVE)
 Values
   (3185, 1862, 'BrksStatement_temp.rtf', 'BRKS_STAT_ACCOUNT_RPT', 'Broker Statement Account', 
    'BrksStatement_temp.xsl', NULL, 'A');
COMMIT;

END;
/

--REGISTERS REPORT PARAMETERS--

begin
Insert into TQC_SYS_RPT_PARAMETERS
   (RPTP_CODE, RPTP_RPT_CODE, RPTP_PARAM_NAME, RPTP_PARAM_DESC, RPTP_PARAM_PROMPT, 
    RPTP_PARAM_TYPE, RPTP_PARENT_CODE, RPTP_QUERY, RPTP_PARAM_CLAUSE, RPTP_USER_REQUIRED, 
    RPTP_CHILD_CODE)
 Values
   (24455, 1862, 'START_DATE', 'START_DATE', 'Start Date', 
    'DATE', NULL, NULL, NULL, NULL, 
    NULL);
Insert into TQC_SYS_RPT_PARAMETERS
   (RPTP_CODE, RPTP_RPT_CODE, RPTP_PARAM_NAME, RPTP_PARAM_DESC, RPTP_PARAM_PROMPT, 
    RPTP_PARAM_TYPE, RPTP_PARENT_CODE, RPTP_QUERY, RPTP_PARAM_CLAUSE, RPTP_USER_REQUIRED, 
    RPTP_CHILD_CODE)
 Values
   (24456,1862, 'END_DATE', 'END_DATE', 'End Date', 
    'DATE', NULL, NULL, NULL, NULL, 
    NULL);
COMMIT;
end;
/