begin

Insert into TQC_SYSTEM_REPORTS
   (RPT_CODE, RPT_SYS_CODE, RPT_NAME, RPT_DESCRIPTION, RPT_DATA_FILE, 
    RPT_APPLCTN_LEVEL, RPT_ACTIVE)
 Values
   (1859, 27, 'BROKER_OUT_PMYT', 'Broker outstanding payment', 'brkOutPmyt.xml', 
    NULL, 'A');
Insert into TQC_SYS_RPT_TEMPLATES
   (RPT_TMPL_CODE, RPT_TMPL_RPT_CODE, RPT_TMPL_FILE, RPT_TMPL_NAME, RPT_TMPL_DESCRIPTION, 
    RPT_TMPL_STYLE_FILE, RPT_TMPL_ORG_CODE, RPT_TMPL_ACTIVE)
 Values
   (3182, 1859, 'brkOutPmyt_temp.rtf', 'BROKER_OUT_PMYT_TEMPLATE', 'Broker outstanding payment template', 
    'brkOutPmyt_temp.xsl', NULL, 'A');

COMMIT;

end;
/



begin
INSERT INTO TQC_SYS_RPT_PARAMETERS ( RPTP_CODE, RPTP_RPT_CODE, RPTP_PARAM_NAME, RPTP_PARAM_DESC,
RPTP_PARAM_PROMPT, RPTP_PARAM_TYPE, RPTP_PARENT_CODE, RPTP_QUERY, RPTP_PARAM_CLAUSE,
RPTP_USER_REQUIRED ) VALUES (
24332,1859, 'START_DATE', 'START_DATE', 'Start Date', 'DATE', NULL,NULL
, NULL, NULL);
INSERT INTO TQC_SYS_RPT_PARAMETERS ( RPTP_CODE, RPTP_RPT_CODE, RPTP_PARAM_NAME, RPTP_PARAM_DESC,
RPTP_PARAM_PROMPT, RPTP_PARAM_TYPE, RPTP_PARENT_CODE, RPTP_QUERY, RPTP_PARAM_CLAUSE,
RPTP_USER_REQUIRED ) VALUES (
24333,1859, 'END_DATE', 'END_DATE', 'End Date', 'DATE', NULL,NULL
, NULL, NULL);
commit;
end;
/
