SET DEFINE OFF;
Insert into LMS_BUSINESS_TRANSACTIONS
   (BTR_TRANS_CODE, BTR_TRANS_TYPE, BTR_DEBIT_CODE, BTR_CREDIT_CODE, BTR_CLM_UW, 
    BTR_WEB_GROUPING)
 Values
   ('CLR', 'CHANGE OF LOAN REPAYMENT', 'CLRD', 'CLRC', 'U', 
    NULL);
COMMIT;

SET DEFINE OFF;
Insert into TQC_SYS_PROCESSES
   (SPRC_CODE, SPRC_SYS_CODE, SPRC_PROCESS, SPRC_BPM_ID, SPRC_SHT_DESC, 
    SPRC_JPDL_DESC)
 Values
   (701, 27, 'CHANGE LOAN REPAYMENT PROCESS', NULL, 'UWCLR', 
    'EndorsementsProcess');
COMMIT;

SET DEFINE OFF;
Insert into TQC_SYS_PROCESS_AREAS
   (SPRCA_CODE, SPRCA_SPRC_CODE, SPRCA_AREA, SPRCA_SHT_DESC)
 Values
   (1474, 701, 'CHANGE LOAN REPAYMENT PROCESS ACCESS', 'ACCS');
Insert into TQC_SYS_PROCESS_AREAS
   (SPRCA_CODE, SPRCA_SPRC_CODE, SPRCA_AREA, SPRCA_SHT_DESC)
 Values
   (1475, 701, 'CHANGE LOAN REPAYMENT UNDEWRITING', 'DENTR');
Insert into TQC_SYS_PROCESS_AREAS
   (SPRCA_CODE, SPRCA_SPRC_CODE, SPRCA_AREA, SPRCA_SHT_DESC)
 Values
   (1476, 701, 'CHANGE LOAN REPAYMENT UNDEWRITING', 'CLRUW');
Insert into TQC_SYS_PROCESS_AREAS
   (SPRCA_CODE, SPRCA_SPRC_CODE, SPRCA_AREA, SPRCA_SHT_DESC)
 Values
   (1477, 701, 'CHANGE LOAN REPAYMENT DISPATCH', 'EDISP');
COMMIT;
SET DEFINE OFF;
Insert into TQC_SYS_PROCESS_SUB_AREAS
   (SPRSA_CODE, SPRSA_SPRCA_CODE, SPRSA_SPRC_CODE, SPRSA_SUB_AREA, SPRSA_TYPE, 
    SPRSA_SHT_DESC, SPRSA_DEFAULT_USR_CODE)
 Values
   (1760, 1474, 701, 'CHANGE LOAN REPAYMENT ACCESS', 'C', 
    'ACCS', NULL);
Insert into TQC_SYS_PROCESS_SUB_AREAS
   (SPRSA_CODE, SPRSA_SPRCA_CODE, SPRSA_SPRC_CODE, SPRSA_SUB_AREA, SPRSA_TYPE, 
    SPRSA_SHT_DESC, SPRSA_DEFAULT_USR_CODE)
 Values
   (1761, 1475, 701, 'CHANGE LOAN REPAYMENT DETAILS', 'C', 
    'CLRDAT', NULL);
Insert into TQC_SYS_PROCESS_SUB_AREAS
   (SPRSA_CODE, SPRSA_SPRCA_CODE, SPRSA_SPRC_CODE, SPRSA_SUB_AREA, SPRSA_TYPE, 
    SPRSA_SHT_DESC, SPRSA_DEFAULT_USR_CODE)
 Values
   (1762, 1476, 701, 'CLR UW PROCESSING', 'C', 
    'CLRUW', NULL);
Insert into TQC_SYS_PROCESS_SUB_AREAS
   (SPRSA_CODE, SPRSA_SPRCA_CODE, SPRSA_SPRC_CODE, SPRSA_SUB_AREA, SPRSA_TYPE, 
    SPRSA_SHT_DESC, SPRSA_DEFAULT_USR_CODE)
 Values
   (1763, 1476, 701, 'CLR UW MAKE READY', 'A', 
    'CLRMR', NULL);
Insert into TQC_SYS_PROCESS_SUB_AREAS
   (SPRSA_CODE, SPRSA_SPRCA_CODE, SPRSA_SPRC_CODE, SPRSA_SUB_AREA, SPRSA_TYPE, 
    SPRSA_SHT_DESC, SPRSA_DEFAULT_USR_CODE)
 Values
   (1764, 1476, 701, 'CLR AUTHORIZATION', 'A', 
    'CLRAU', NULL);
Insert into TQC_SYS_PROCESS_SUB_AREAS
   (SPRSA_CODE, SPRSA_SPRCA_CODE, SPRSA_SPRC_CODE, SPRSA_SUB_AREA, SPRSA_TYPE, 
    SPRSA_SHT_DESC, SPRSA_DEFAULT_USR_CODE)
 Values
   (1765, 1477, 701, 'POLICY DOCUMENTS DISPATCH', 'C', 
    'EDISP', NULL);
COMMIT;
