begin
Insert into TQC_SYS_RPT_TEMPLATES
   (RPT_TMPL_CODE, RPT_TMPL_RPT_CODE, RPT_TMPL_FILE, RPT_TMPL_NAME, RPT_TMPL_DESCRIPTION, 
    RPT_TMPL_STYLE_FILE, RPT_TMPL_ORG_CODE, RPT_TMPL_ACTIVE)
 Values
   (3187,1249, 'reduenot1MNR_temp.rtf', 'REN_NOTE_RWA_TMP', 'Renewal Notice RWA', 
    'reduenot1MNR_temp.xsl', NULL, 'A');
COMMIT;
end;
/